.PHONY : all targets

all: targets
libobj8=EB.BP]MOBJECT/isSeparator.so EB.BP]MOBJECT/isSpacer.so EB.BP]MOBJECT/isString.so EB.BP]MOBJECT/lexLine.so EB.BP]MOBJECT/nextToken.so EB.BP]MOBJECT/stringType.so EB.BP]MOBJECT/ttvt220_TRANS.so
libobj7=EB.BP]MOBJECT/SVN_CLEAN.so EB.BP]MOBJECT/SVN_COMMIT.so EB.BP]MOBJECT/SVN_DELETE.so EB.BP]MOBJECT/SVN_EXEC.so EB.BP]MOBJECT/SVN_GETCATLID.so EB.BP]MOBJECT/SVN_GETHOMEPATH.so EB.BP]MOBJECT/SVN_GETORIGPATH.so EB.BP]MOBJECT/SVN_GETPWD.so EB.BP]MOBJECT/SVN_GETROOT.so EB.BP]MOBJECT/SVN_GET_REPOSITORY.so EB.BP]MOBJECT/SVN_HISTORY.so EB.BP]MOBJECT/SVN_READ.so EB.BP]MOBJECT/SVN_REPOSITORY.so EB.BP]MOBJECT/SVN_REVERT.so EB.BP]MOBJECT/SVN_SRC_STATUS.so EB.BP]MOBJECT/SVN_SYNC.so EB.BP]MOBJECT/initColors.so EB.BP]MOBJECT/isComment.so EB.BP]MOBJECT/isNumber.so EB.BP]MOBJECT/isReservedWord.so
libobj6=EB.BP]MOBJECT/SRC_GETHOMEPATH.so EB.BP]MOBJECT/SRC_GETORIGPATH.so EB.BP]MOBJECT/SRC_GETPWD.so EB.BP]MOBJECT/SRC_GETROOT.so EB.BP]MOBJECT/SRC_GET_REPOSITORY.so EB.BP]MOBJECT/SRC_HISTORY.so EB.BP]MOBJECT/SRC_OPENHIST.so EB.BP]MOBJECT/SRC_OPENLOCKS.so EB.BP]MOBJECT/SRC_READ.so EB.BP]MOBJECT/SRC_READHIST.so EB.BP]MOBJECT/SRC_REMOVEHIST.so EB.BP]MOBJECT/SRC_REPOSITORY.so EB.BP]MOBJECT/SRC_REVERT.so EB.BP]MOBJECT/SRC_SENTENCE.so EB.BP]MOBJECT/SRC_SRC_STATUS.so EB.BP]MOBJECT/SRC_SYNC.so EB.BP]MOBJECT/SRC_UPDATEHIST.so EB.BP]MOBJECT/SVN_ADD.so EB.BP]MOBJECT/SVN_CHECKIN.so EB.BP]MOBJECT/SVN_CHECKOUT.so
libobj5=EB.BP]MOBJECT/GIT_GETROOT.so EB.BP]MOBJECT/GIT_GET_REPOSITORY.so EB.BP]MOBJECT/GIT_HISTORY.so EB.BP]MOBJECT/GIT_READ.so EB.BP]MOBJECT/GIT_REPOSITORY.so EB.BP]MOBJECT/GIT_REVERT.so EB.BP]MOBJECT/GIT_SRC_STATUS.so EB.BP]MOBJECT/GIT_SYNC.so EB.BP]MOBJECT/JBCUserConversions.so EB.BP]MOBJECT/SPLITFILEPATH.so EB.BP]MOBJECT/SRCPUSH.so EB.BP]MOBJECT/SRC_ADD.so EB.BP]MOBJECT/SRC_CASE.so EB.BP]MOBJECT/SRC_CHECKIN.so EB.BP]MOBJECT/SRC_CHECKOUT.so EB.BP]MOBJECT/SRC_CLEAN.so EB.BP]MOBJECT/SRC_COMMIT.so EB.BP]MOBJECT/SRC_DELETE.so EB.BP]MOBJECT/SRC_EXEC.so EB.BP]MOBJECT/SRC_GETCATLID.so
libobj4=EB.BP]MOBJECT/EB_VERSION.so EB.BP]MOBJECT/EB_VERS_CTRL.so EB.BP]MOBJECT/FNKEYTRANS.so EB.BP]MOBJECT/GETFLNM.so EB.BP]MOBJECT/GETFULLPATH.so EB.BP]MOBJECT/GETSRCTYPE.so EB.BP]MOBJECT/GETYN.so EB.BP]MOBJECT/GET_CATALOG_FILE.so EB.BP]MOBJECT/GET_CATALOG_FILES.so EB.BP]MOBJECT/GIT_ADD.so EB.BP]MOBJECT/GIT_CHECKIN.so EB.BP]MOBJECT/GIT_CHECKOUT.so EB.BP]MOBJECT/GIT_CLEAN.so EB.BP]MOBJECT/GIT_COMMIT.so EB.BP]MOBJECT/GIT_DELETE.so EB.BP]MOBJECT/GIT_EXEC.so EB.BP]MOBJECT/GIT_GETCATLID.so EB.BP]MOBJECT/GIT_GETHOMEPATH.so EB.BP]MOBJECT/GIT_GETORIGPATH.so EB.BP]MOBJECT/GIT_GETPWD.so
libobj3=EB.BP]MOBJECT/EB_READHEADERS.so EB.BP]MOBJECT/EB_READINCL.so EB.BP]MOBJECT/EB_REFINE.so EB.BP]MOBJECT/EB_REFRESH.so EB.BP]MOBJECT/EB_REGEX.so EB.BP]MOBJECT/EB_REPLACE.so EB.BP]MOBJECT/EB_ROTATE.so EB.BP]MOBJECT/EB_RSS.so EB.BP]MOBJECT/EB_SEARCH.so EB.BP]MOBJECT/EB_SETUPSWITCH.so EB.BP]MOBJECT/EB_SHOWMEMBERS.so EB.BP]MOBJECT/EB_SWAP.so EB.BP]MOBJECT/EB_TABCOL.so EB.BP]MOBJECT/EB_TABS.so EB.BP]MOBJECT/EB_TCL.so EB.BP]MOBJECT/EB_TRIM.so EB.BP]MOBJECT/EB_UT_BOX.so EB.BP]MOBJECT/EB_UT_INIT.so EB.BP]MOBJECT/EB_UT_INPUT_ZERO.so EB.BP]MOBJECT/EB_UT_WP.so
libobj2=EB.BP]MOBJECT/EB_FORMAT.so EB.BP]MOBJECT/EB_GETMOUSE.so EB.BP]MOBJECT/EB_GETRPL.so EB.BP]MOBJECT/EB_GETTCC.so EB.BP]MOBJECT/EB_GET_INPUT.so EB.BP]MOBJECT/EB_HELP.so EB.BP]MOBJECT/EB_INP.so EB.BP]MOBJECT/EB_INPUT.so EB.BP]MOBJECT/EB_INPUT_ZERO.so EB.BP]MOBJECT/EB_INTEGRATE.so EB.BP]MOBJECT/EB_LOWER.so EB.BP]MOBJECT/EB_MAKEHIST.so EB.BP]MOBJECT/EB_MARKADJ.so EB.BP]MOBJECT/EB_MERGE.so EB.BP]MOBJECT/EB_MERRMSG.so EB.BP]MOBJECT/EB_MOVE.so EB.BP]MOBJECT/EB_OPEN.so EB.BP]MOBJECT/EB_OPEN_FILE.so EB.BP]MOBJECT/EB_PASTE.so EB.BP]MOBJECT/EB_PRINT.so
libobj1=EB.BP]MOBJECT/EBGETHOME.so EB.BP]MOBJECT/EBGETKEY.so EB.BP]MOBJECT/EBJSHOW.so EB.BP]MOBJECT/EB_ADD.so EB.BP]MOBJECT/EB_ANCHAR.so EB.BP]MOBJECT/EB_ASSIGN_OPEN.so EB.BP]MOBJECT/EB_AUTOSAVE.so EB.BP]MOBJECT/EB_BOX.so EB.BP]MOBJECT/EB_CHOICES.so EB.BP]MOBJECT/EB_CH_COLOUR.so EB.BP]MOBJECT/EB_CLOSE.so EB.BP]MOBJECT/EB_COMPARE.so EB.BP]MOBJECT/EB_CONVCODE.so EB.BP]MOBJECT/EB_CUT.so EB.BP]MOBJECT/EB_EREPLACE.so EB.BP]MOBJECT/EB_ERRMSG.so EB.BP]MOBJECT/EB_EXPANDFLNM.so EB.BP]MOBJECT/EB_FILE.so EB.BP]MOBJECT/EB_FIND.so EB.BP]MOBJECT/EB_FINDDEC.so
bin2=./bin/GITREVERT ./bin/GITSELECT ./bin/LASTEB ./bin/SRCCHECKOUT ./bin/SRCCOMMIT ./bin/SRCDELETE ./bin/SRCRENAME ./bin/SRCREVERT ./bin/SRCSELECT ./bin/SVNCHECKOUT ./bin/SVNCOMMIT ./bin/SVNDELETE ./bin/SVNRENAME ./bin/SVNREVERT ./bin/SVNSELECT ./bin/UNCOMPILED ./bin/color ./bin/jEDIfmt ./bin/lexTest
bin1=./bin/COMPARE_ITEM ./bin/COMPL ./bin/COMPL2 ./bin/CONVF2DIR ./bin/D3BASIC ./bin/EB ./bin/EBCRT ./bin/EBFIND ./bin/EBKEYS ./bin/EBKEYTEST ./bin/EBL ./bin/EBTTCOPY ./bin/EBV ./bin/EB_BGCOMPILE ./bin/EB_ENABLE ./bin/GETSAME ./bin/GITCHECKOUT ./bin/GITCOMMIT ./bin/GITDELETE ./bin/GITRENAME
lib8=./lib/isSeparator.so ./lib/isSpacer.so ./lib/isString.so ./lib/lexLine.so ./lib/nextToken.so ./lib/stringType.so ./lib/ttvt220_TRANS.so
lib7=./lib/SVN_CLEAN.so ./lib/SVN_COMMIT.so ./lib/SVN_DELETE.so ./lib/SVN_EXEC.so ./lib/SVN_GETCATLID.so ./lib/SVN_GETHOMEPATH.so ./lib/SVN_GETORIGPATH.so ./lib/SVN_GETPWD.so ./lib/SVN_GETROOT.so ./lib/SVN_GET_REPOSITORY.so ./lib/SVN_HISTORY.so ./lib/SVN_READ.so ./lib/SVN_REPOSITORY.so ./lib/SVN_REVERT.so ./lib/SVN_SRC_STATUS.so ./lib/SVN_SYNC.so ./lib/initColors.so ./lib/isComment.so ./lib/isNumber.so ./lib/isReservedWord.so
lib6=./lib/SRC_GETHOMEPATH.so ./lib/SRC_GETORIGPATH.so ./lib/SRC_GETPWD.so ./lib/SRC_GETROOT.so ./lib/SRC_GET_REPOSITORY.so ./lib/SRC_HISTORY.so ./lib/SRC_OPENHIST.so ./lib/SRC_OPENLOCKS.so ./lib/SRC_READ.so ./lib/SRC_READHIST.so ./lib/SRC_REMOVEHIST.so ./lib/SRC_REPOSITORY.so ./lib/SRC_REVERT.so ./lib/SRC_SENTENCE.so ./lib/SRC_SRC_STATUS.so ./lib/SRC_SYNC.so ./lib/SRC_UPDATEHIST.so ./lib/SVN_ADD.so ./lib/SVN_CHECKIN.so ./lib/SVN_CHECKOUT.so
lib5=./lib/GIT_GETROOT.so ./lib/GIT_GET_REPOSITORY.so ./lib/GIT_HISTORY.so ./lib/GIT_READ.so ./lib/GIT_REPOSITORY.so ./lib/GIT_REVERT.so ./lib/GIT_SRC_STATUS.so ./lib/GIT_SYNC.so ./lib/JBCUserConversions.so ./lib/SPLITFILEPATH.so ./lib/SRCPUSH.so ./lib/SRC_ADD.so ./lib/SRC_CASE.so ./lib/SRC_CHECKIN.so ./lib/SRC_CHECKOUT.so ./lib/SRC_CLEAN.so ./lib/SRC_COMMIT.so ./lib/SRC_DELETE.so ./lib/SRC_EXEC.so ./lib/SRC_GETCATLID.so
lib4=./lib/EB_VERSION.so ./lib/EB_VERS_CTRL.so ./lib/FNKEYTRANS.so ./lib/GETFLNM.so ./lib/GETFULLPATH.so ./lib/GETSRCTYPE.so ./lib/GETYN.so ./lib/GET_CATALOG_FILE.so ./lib/GET_CATALOG_FILES.so ./lib/GIT_ADD.so ./lib/GIT_CHECKIN.so ./lib/GIT_CHECKOUT.so ./lib/GIT_CLEAN.so ./lib/GIT_COMMIT.so ./lib/GIT_DELETE.so ./lib/GIT_EXEC.so ./lib/GIT_GETCATLID.so ./lib/GIT_GETHOMEPATH.so ./lib/GIT_GETORIGPATH.so ./lib/GIT_GETPWD.so
lib3=./lib/EB_READHEADERS.so ./lib/EB_READINCL.so ./lib/EB_REFINE.so ./lib/EB_REFRESH.so ./lib/EB_REGEX.so ./lib/EB_REPLACE.so ./lib/EB_ROTATE.so ./lib/EB_RSS.so ./lib/EB_SEARCH.so ./lib/EB_SETUPSWITCH.so ./lib/EB_SHOWMEMBERS.so ./lib/EB_SWAP.so ./lib/EB_TABCOL.so ./lib/EB_TABS.so ./lib/EB_TCL.so ./lib/EB_TRIM.so ./lib/EB_UT_BOX.so ./lib/EB_UT_INIT.so ./lib/EB_UT_INPUT_ZERO.so ./lib/EB_UT_WP.so
lib2=./lib/EB_FORMAT.so ./lib/EB_GETMOUSE.so ./lib/EB_GETRPL.so ./lib/EB_GETTCC.so ./lib/EB_GET_INPUT.so ./lib/EB_HELP.so ./lib/EB_INP.so ./lib/EB_INPUT.so ./lib/EB_INPUT_ZERO.so ./lib/EB_INTEGRATE.so ./lib/EB_LOWER.so ./lib/EB_MAKEHIST.so ./lib/EB_MARKADJ.so ./lib/EB_MERGE.so ./lib/EB_MERRMSG.so ./lib/EB_MOVE.so ./lib/EB_OPEN.so ./lib/EB_OPEN_FILE.so ./lib/EB_PASTE.so ./lib/EB_PRINT.so
lib1=./lib/EBGETHOME.so ./lib/EBGETKEY.so ./lib/EBJSHOW.so ./lib/EB_ADD.so ./lib/EB_ANCHAR.so ./lib/EB_ASSIGN_OPEN.so ./lib/EB_AUTOSAVE.so ./lib/EB_BOX.so ./lib/EB_CHOICES.so ./lib/EB_CH_COLOUR.so ./lib/EB_CLOSE.so ./lib/EB_COMPARE.so ./lib/EB_CONVCODE.so ./lib/EB_CUT.so ./lib/EB_EREPLACE.so ./lib/EB_ERRMSG.so ./lib/EB_EXPANDFLNM.so ./lib/EB_FILE.so ./lib/EB_FIND.so ./lib/EB_FINDDEC.so
binobj2=EB.BP]MOBJECT/GITREVERT.so EB.BP]MOBJECT/GITSELECT.so EB.BP]MOBJECT/LASTEB.so EB.BP]MOBJECT/SRCCHECKOUT.so EB.BP]MOBJECT/SRCCOMMIT.so EB.BP]MOBJECT/SRCDELETE.so EB.BP]MOBJECT/SRCRENAME.so EB.BP]MOBJECT/SRCREVERT.so EB.BP]MOBJECT/SRCSELECT.so EB.BP]MOBJECT/SVNCHECKOUT.so EB.BP]MOBJECT/SVNCOMMIT.so EB.BP]MOBJECT/SVNDELETE.so EB.BP]MOBJECT/SVNRENAME.so EB.BP]MOBJECT/SVNREVERT.so EB.BP]MOBJECT/SVNSELECT.so EB.BP]MOBJECT/UNCOMPILED.so EB.BP]MOBJECT/color.so EB.BP]MOBJECT/jEDIfmt.so EB.BP]MOBJECT/lexTest.so
binobj1=EB.BP]MOBJECT/COMPARE_ITEM.so EB.BP]MOBJECT/COMPL.so EB.BP]MOBJECT/COMPL2.so EB.BP]MOBJECT/CONVF2DIR.so EB.BP]MOBJECT/D3BASIC.so EB.BP]MOBJECT/EB.so EB.BP]MOBJECT/EBCRT.so EB.BP]MOBJECT/EBFIND.so EB.BP]MOBJECT/EBKEYS.so EB.BP]MOBJECT/EBKEYTEST.so EB.BP]MOBJECT/EBL.so EB.BP]MOBJECT/EBTTCOPY.so EB.BP]MOBJECT/EBV.so EB.BP]MOBJECT/EB_BGCOMPILE.so EB.BP]MOBJECT/EB_ENABLE.so EB.BP]MOBJECT/GETSAME.so EB.BP]MOBJECT/GITCHECKOUT.so EB.BP]MOBJECT/GITCOMMIT.so EB.BP]MOBJECT/GITDELETE.so EB.BP]MOBJECT/GITRENAME.so
binobjs=$(binobj2) $(binobj1)
libobjs=$(libobj8) $(libobj7) $(libobj6) $(libobj5) $(libobj4) $(libobj3) $(libobj2) $(libobj1)

alllibs: $(libobjs)
	make -s  $(lib8) $(lib7) $(lib6) $(lib5) $(lib4) $(lib3) $(lib2) $(lib1)

targets: allbins alllibs

allbins: $(binobjs)
	make -s $(bin2) $(bin1)


EB.BP]MOBJECT/COMPARE_ITEM.so: EB.BP/COMPARE_ITEM.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/CLEARSELECT EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/FIND.NEXT.DIFF EB.OS.INCLUDES/GET.FLNM EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/WHO
	BASIC EB.BP COMPARE_ITEM.b

./bin/COMPARE_ITEM: EB.BP]MOBJECT/COMPARE_ITEM.so
	CATALOG -o./bin EB.BP COMPARE_ITEM.b

EB.BP]MOBJECT/COMPL.so: EB.BP/COMPL.b
	BASIC EB.BP COMPL.b

./bin/COMPL: EB.BP]MOBJECT/COMPL.so
	CATALOG -o./bin EB.BP COMPL.b

EB.BP]MOBJECT/COMPL2.so: EB.BP/COMPL2.b
	BASIC EB.BP COMPL2.b

./bin/COMPL2: EB.BP]MOBJECT/COMPL2.so
	CATALOG -o./bin EB.BP COMPL2.b

EB.BP]MOBJECT/CONVF2DIR.so: EB.BP/CONVF2DIR.b
	BASIC EB.BP CONVF2DIR.b

./bin/CONVF2DIR: EB.BP]MOBJECT/CONVF2DIR.so
	CATALOG -o./bin EB.BP CONVF2DIR.b

EB.BP]MOBJECT/D3BASIC.so: EB.BP/D3BASIC.b
	BASIC EB.BP D3BASIC.b

./bin/D3BASIC: EB.BP]MOBJECT/D3BASIC.so
	CATALOG -o./bin EB.BP D3BASIC.b

EB.BP]MOBJECT/EB.so: EB.BP/EB.b EB.EQUS/ACT.CODES EB.EQUS/COLOUR.CODES EB.EQUS/COLOURS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CHECK.B EB.INCLUDES/CRT.LN EB.INCLUDES/EB.CASE EB.INCLUDES/VERS_CTRL EB.INCLUDES/cReserved.h EB.INCLUDES/jbcReserved.h EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/BACKGROUND.VERB EB.OS.INCLUDES/BASIC.OPTS EB.OS.INCLUDES/BASIC.VERB EB.OS.INCLUDES/CATALOG EB.OS.INCLUDES/CLEARSELECT EB.OS.INCLUDES/DECATALOG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/EB.INIT EB.OS.INCLUDES/EB.LMARGIN EB.OS.INCLUDES/EB.SQL EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/GET.FLNM EB.OS.INCLUDES/GET.TCL.SENTENCE EB.OS.INCLUDES/LOCKED.BY EB.OS.INCLUDES/OS EB.OS.INCLUDES/OS.ERRORS EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/RTED.BASIC EB.OS.INCLUDES/SET.TIMEOUT EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/TIMEOUT.OFF EB.OS.INCLUDES/TIMEOUT.ON EB.OS.INCLUDES/WHO
	BASIC EB.BP EB.b

./bin/EB: EB.BP]MOBJECT/EB.so
	CATALOG -o./bin EB.BP EB.b
	cp ./bin/EB ./bin/eb
	cp ./bin/EB.so ./bin/eb.so

EB.BP]MOBJECT/EBCRT.so: EB.BP/EBCRT.b EB.EQUS/SCREEN.PARAMS
	BASIC EB.BP EBCRT.b

./bin/EBCRT: EB.BP]MOBJECT/EBCRT.so
	CATALOG -o./bin EB.BP EBCRT.b

EB.BP]MOBJECT/EBFIND.so: EB.BP/EBFIND.b
	BASIC EB.BP EBFIND.b

./bin/EBFIND: EB.BP]MOBJECT/EBFIND.so
	CATALOG -o./bin EB.BP EBFIND.b

EB.BP]MOBJECT/EBGETHOME.so: EB.BP/EBGETHOME.b
	BASIC EB.BP EBGETHOME.b

./lib/EBGETHOME.so: EB.BP]MOBJECT/EBGETHOME.so
	CATALOG -L./lib EB.BP EBGETHOME.b

EB.BP]MOBJECT/EBGETKEY.so: EB.BP/EBGETKEY.b
	BASIC EB.BP EBGETKEY.b

./lib/EBGETKEY.so: EB.BP]MOBJECT/EBGETKEY.so
	CATALOG -L./lib EB.BP EBGETKEY.b

EB.BP]MOBJECT/EBJSHOW.so: EB.BP/EBJSHOW.b
	BASIC EB.BP EBJSHOW.b

./lib/EBJSHOW.so: EB.BP]MOBJECT/EBJSHOW.so
	CATALOG -L./lib EB.BP EBJSHOW.b

EB.BP]MOBJECT/EBKEYS.so: EB.BP/EBKEYS.b EB.EQUS/EB.CHARS
	BASIC EB.BP EBKEYS.b

./bin/EBKEYS: EB.BP]MOBJECT/EBKEYS.so
	CATALOG -o./bin EB.BP EBKEYS.b

EB.BP]MOBJECT/EBKEYTEST.so: EB.BP/EBKEYTEST.b
	BASIC EB.BP EBKEYTEST.b

./bin/EBKEYTEST: EB.BP]MOBJECT/EBKEYTEST.so
	CATALOG -o./bin EB.BP EBKEYTEST.b

EB.BP]MOBJECT/EBL.so: EB.BP/EBL.b EB.OS.INCLUDES/GET.TCL.SENTENCE EB.OS.INCLUDES/OS EB.OS.INCLUDES/WHO
	BASIC EB.BP EBL.b

./bin/EBL: EB.BP]MOBJECT/EBL.so
	CATALOG -o./bin EB.BP EBL.b

EB.BP]MOBJECT/EBTTCOPY.so: EB.BP/EBTTCOPY.b
	BASIC EB.BP EBTTCOPY.b

./bin/EBTTCOPY: EB.BP]MOBJECT/EBTTCOPY.so
	CATALOG -o./bin EB.BP EBTTCOPY.b

EB.BP]MOBJECT/EBV.so: EB.BP/EBV.b
	BASIC EB.BP EBV.b

./bin/EBV: EB.BP]MOBJECT/EBV.so
	CATALOG -o./bin EB.BP EBV.b

EB.BP]MOBJECT/EB_ADD.so: EB.BP/EB_ADD.b
	BASIC EB.BP EB_ADD.b

./lib/EB_ADD.so: EB.BP]MOBJECT/EB_ADD.so
	CATALOG -L./lib EB.BP EB_ADD.b

EB.BP]MOBJECT/EB_ANCHAR.so: EB.BP/EB_ANCHAR.b
	BASIC EB.BP EB_ANCHAR.b

./lib/EB_ANCHAR.so: EB.BP]MOBJECT/EB_ANCHAR.so
	CATALOG -L./lib EB.BP EB_ANCHAR.b

EB.BP]MOBJECT/EB_ASSIGN_OPEN.so: EB.BP/EB_ASSIGN_OPEN.b EB.EQUS/EB.COMMONS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_ASSIGN_OPEN.b

./lib/EB_ASSIGN_OPEN.so: EB.BP]MOBJECT/EB_ASSIGN_OPEN.so
	CATALOG -L./lib EB.BP EB_ASSIGN_OPEN.b

EB.BP]MOBJECT/EB_AUTOSAVE.so: EB.BP/EB_AUTOSAVE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_AUTOSAVE.b

./lib/EB_AUTOSAVE.so: EB.BP]MOBJECT/EB_AUTOSAVE.so
	CATALOG -L./lib EB.BP EB_AUTOSAVE.b

EB.BP]MOBJECT/EB_BGCOMPILE.so: EB.BP/EB_BGCOMPILE.b
	BASIC EB.BP EB_BGCOMPILE.b

./bin/EB_BGCOMPILE: EB.BP]MOBJECT/EB_BGCOMPILE.so
	CATALOG -o./bin EB.BP EB_BGCOMPILE.b

EB.BP]MOBJECT/EB_BOX.so: EB.BP/EB_BOX.b EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_BOX.b

./lib/EB_BOX.so: EB.BP]MOBJECT/EB_BOX.so
	CATALOG -L./lib EB.BP EB_BOX.b

EB.BP]MOBJECT/EB_CHOICES.so: EB.BP/EB_CHOICES.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/DRV.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/REFRESH.CODES EB.EQUS/SCR.CRT.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/USER.EXITS
	BASIC EB.BP EB_CHOICES.b

./lib/EB_CHOICES.so: EB.BP]MOBJECT/EB_CHOICES.so
	CATALOG -L./lib EB.BP EB_CHOICES.b

EB.BP]MOBJECT/EB_CH_COLOUR.so: EB.BP/EB_CH_COLOUR.b
	BASIC EB.BP EB_CH_COLOUR.b

./lib/EB_CH_COLOUR.so: EB.BP]MOBJECT/EB_CH_COLOUR.so
	CATALOG -L./lib EB.BP EB_CH_COLOUR.b

EB.BP]MOBJECT/EB_CLOSE.so: EB.BP/EB_CLOSE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_CLOSE.b

./lib/EB_CLOSE.so: EB.BP]MOBJECT/EB_CLOSE.so
	CATALOG -L./lib EB.BP EB_CLOSE.b

EB.BP]MOBJECT/EB_COMPARE.so: EB.BP/EB_COMPARE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_COMPARE.b

./lib/EB_COMPARE.so: EB.BP]MOBJECT/EB_COMPARE.so
	CATALOG -L./lib EB.BP EB_COMPARE.b

EB.BP]MOBJECT/EB_CONVCODE.so: EB.BP/EB_CONVCODE.b EB.EQUS/ACT.CODES
	BASIC EB.BP EB_CONVCODE.b

./lib/EB_CONVCODE.so: EB.BP]MOBJECT/EB_CONVCODE.so
	CATALOG -L./lib EB.BP EB_CONVCODE.b

EB.BP]MOBJECT/EB_CUT.so: EB.BP/EB_CUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_CUT.b

./lib/EB_CUT.so: EB.BP]MOBJECT/EB_CUT.so
	CATALOG -L./lib EB.BP EB_CUT.b

EB.BP]MOBJECT/EB_ENABLE.so: EB.BP/EB_ENABLE.b
	BASIC EB.BP EB_ENABLE.b

./bin/EB_ENABLE: EB.BP]MOBJECT/EB_ENABLE.so
	CATALOG -o./bin EB.BP EB_ENABLE.b

EB.BP]MOBJECT/EB_EREPLACE.so: EB.BP/EB_EREPLACE.b
	BASIC EB.BP EB_EREPLACE.b

./lib/EB_EREPLACE.so: EB.BP]MOBJECT/EB_EREPLACE.so
	CATALOG -L./lib EB.BP EB_EREPLACE.b

EB.BP]MOBJECT/EB_ERRMSG.so: EB.BP/EB_ERRMSG.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_ERRMSG.b

./lib/EB_ERRMSG.so: EB.BP]MOBJECT/EB_ERRMSG.so
	CATALOG -L./lib EB.BP EB_ERRMSG.b

EB.BP]MOBJECT/EB_EXPANDFLNM.so: EB.BP/EB_EXPANDFLNM.b EB.INCLUDES/PWD
	BASIC EB.BP EB_EXPANDFLNM.b

./lib/EB_EXPANDFLNM.so: EB.BP]MOBJECT/EB_EXPANDFLNM.so
	CATALOG -L./lib EB.BP EB_EXPANDFLNM.b

EB.BP]MOBJECT/EB_FILE.so: EB.BP/EB_FILE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS
	BASIC EB.BP EB_FILE.b

./lib/EB_FILE.so: EB.BP]MOBJECT/EB_FILE.so
	CATALOG -L./lib EB.BP EB_FILE.b

EB.BP]MOBJECT/EB_FIND.so: EB.BP/EB_FIND.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_FIND.b

./lib/EB_FIND.so: EB.BP]MOBJECT/EB_FIND.so
	CATALOG -L./lib EB.BP EB_FIND.b

EB.BP]MOBJECT/EB_FINDDEC.so: EB.BP/EB_FINDDEC.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_FINDDEC.b

./lib/EB_FINDDEC.so: EB.BP]MOBJECT/EB_FINDDEC.so
	CATALOG -L./lib EB.BP EB_FINDDEC.b

EB.BP]MOBJECT/EB_FORMAT.so: EB.BP/EB_FORMAT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_FORMAT.b

./lib/EB_FORMAT.so: EB.BP]MOBJECT/EB_FORMAT.so
	CATALOG -L./lib EB.BP EB_FORMAT.b

EB.BP]MOBJECT/EB_GETMOUSE.so: EB.BP/EB_GETMOUSE.b
	BASIC EB.BP EB_GETMOUSE.b

./lib/EB_GETMOUSE.so: EB.BP]MOBJECT/EB_GETMOUSE.so
	CATALOG -L./lib EB.BP EB_GETMOUSE.b

EB.BP]MOBJECT/EB_GETRPL.so: EB.BP/EB_GETRPL.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_GETRPL.b

./lib/EB_GETRPL.so: EB.BP]MOBJECT/EB_GETRPL.so
	CATALOG -L./lib EB.BP EB_GETRPL.b

EB.BP]MOBJECT/EB_GETTCC.so: EB.BP/EB_GETTCC.b EB.EQUS/TERM.TYPES
	BASIC EB.BP EB_GETTCC.b

./lib/EB_GETTCC.so: EB.BP]MOBJECT/EB_GETTCC.so
	CATALOG -L./lib EB.BP EB_GETTCC.b

EB.BP]MOBJECT/EB_GET_INPUT.so: EB.BP/EB_GET_INPUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_GET_INPUT.b

./lib/EB_GET_INPUT.so: EB.BP]MOBJECT/EB_GET_INPUT.so
	CATALOG -L./lib EB.BP EB_GET_INPUT.b

EB.BP]MOBJECT/EB_HELP.so: EB.BP/EB_HELP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.REL
	BASIC EB.BP EB_HELP.b

./lib/EB_HELP.so: EB.BP]MOBJECT/EB_HELP.so
	CATALOG -L./lib EB.BP EB_HELP.b

EB.BP]MOBJECT/EB_INP.so: EB.BP/EB_INP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_INP.b

./lib/EB_INP.so: EB.BP]MOBJECT/EB_INP.so
	CATALOG -L./lib EB.BP EB_INP.b

EB.BP]MOBJECT/EB_INPUT.so: EB.BP/EB_INPUT.b EB.EQUS/ACT.CODES EB.EQUS/DRV.PARAMS EB.EQUS/EB.CHARS EB.EQUS/OTHER.PARAMS EB.EQUS/REFRESH.CODES EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/EB.STD.EQUS EB.INCLUDES/EB.WP.SUBROUTINES EB.OS.INCLUDES/AT.MINUS.CODES EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/DATE.CONV EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.DIFF EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.LINE.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/PC.RESET.CURSOR EB.OS.INCLUDES/SYSTEM.12 EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/USER.EXITS EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_INPUT.b

./lib/EB_INPUT.so: EB.BP]MOBJECT/EB_INPUT.so
	CATALOG -L./lib EB.BP EB_INPUT.b

EB.BP]MOBJECT/EB_INPUT_ZERO.so: EB.BP/EB_INPUT_ZERO.b EB.EQUS/ACT.CODES EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/CHECK.SUB.SUB EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.TIMEOUT EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_INPUT_ZERO.b

./lib/EB_INPUT_ZERO.so: EB.BP]MOBJECT/EB_INPUT_ZERO.so
	CATALOG -L./lib EB.BP EB_INPUT_ZERO.b

EB.BP]MOBJECT/EB_INTEGRATE.so: EB.BP/EB_INTEGRATE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_INTEGRATE.b

./lib/EB_INTEGRATE.so: EB.BP]MOBJECT/EB_INTEGRATE.so
	CATALOG -L./lib EB.BP EB_INTEGRATE.b

EB.BP]MOBJECT/EB_LOWER.so: EB.BP/EB_LOWER.b EB.INCLUDES/jbcReserved.h
	BASIC EB.BP EB_LOWER.b

./lib/EB_LOWER.so: EB.BP]MOBJECT/EB_LOWER.so
	CATALOG -L./lib EB.BP EB_LOWER.b

EB.BP]MOBJECT/EB_MAKEHIST.so: EB.BP/EB_MAKEHIST.b
	BASIC EB.BP EB_MAKEHIST.b

./lib/EB_MAKEHIST.so: EB.BP]MOBJECT/EB_MAKEHIST.so
	CATALOG -L./lib EB.BP EB_MAKEHIST.b

EB.BP]MOBJECT/EB_MARKADJ.so: EB.BP/EB_MARKADJ.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_MARKADJ.b

./lib/EB_MARKADJ.so: EB.BP]MOBJECT/EB_MARKADJ.so
	CATALOG -L./lib EB.BP EB_MARKADJ.b

EB.BP]MOBJECT/EB_MERGE.so: EB.BP/EB_MERGE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_MERGE.b

./lib/EB_MERGE.so: EB.BP]MOBJECT/EB_MERGE.so
	CATALOG -L./lib EB.BP EB_MERGE.b

EB.BP]MOBJECT/EB_MERRMSG.so: EB.BP/EB_MERRMSG.b EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.EQUS/WIN.ARGS EB.INCLUDES/MORE.CHARS EB.INCLUDES/REMOVE.TYPEAHEAD EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.14
	BASIC EB.BP EB_MERRMSG.b

./lib/EB_MERRMSG.so: EB.BP]MOBJECT/EB_MERRMSG.so
	CATALOG -L./lib EB.BP EB_MERRMSG.b

EB.BP]MOBJECT/EB_MOVE.so: EB.BP/EB_MOVE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_MOVE.b

./lib/EB_MOVE.so: EB.BP]MOBJECT/EB_MOVE.so
	CATALOG -L./lib EB.BP EB_MOVE.b

EB.BP]MOBJECT/EB_OPEN.so: EB.BP/EB_OPEN.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_OPEN.b

./lib/EB_OPEN.so: EB.BP]MOBJECT/EB_OPEN.so
	CATALOG -L./lib EB.BP EB_OPEN.b

EB.BP]MOBJECT/EB_OPEN_FILE.so: EB.BP/EB_OPEN_FILE.b EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_OPEN_FILE.b

./lib/EB_OPEN_FILE.so: EB.BP]MOBJECT/EB_OPEN_FILE.so
	CATALOG -L./lib EB.BP EB_OPEN_FILE.b

EB.BP]MOBJECT/EB_PASTE.so: EB.BP/EB_PASTE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_PASTE.b

./lib/EB_PASTE.so: EB.BP]MOBJECT/EB_PASTE.so
	CATALOG -L./lib EB.BP EB_PASTE.b

EB.BP]MOBJECT/EB_PRINT.so: EB.BP/EB_PRINT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_PRINT.b

./lib/EB_PRINT.so: EB.BP]MOBJECT/EB_PRINT.so
	CATALOG -L./lib EB.BP EB_PRINT.b

EB.BP]MOBJECT/EB_READHEADERS.so: EB.BP/EB_READHEADERS.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_READHEADERS.b

./lib/EB_READHEADERS.so: EB.BP]MOBJECT/EB_READHEADERS.so
	CATALOG -L./lib EB.BP EB_READHEADERS.b

EB.BP]MOBJECT/EB_READINCL.so: EB.BP/EB_READINCL.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_READINCL.b

./lib/EB_READINCL.so: EB.BP]MOBJECT/EB_READINCL.so
	CATALOG -L./lib EB.BP EB_READINCL.b

EB.BP]MOBJECT/EB_REFINE.so: EB.BP/EB_REFINE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_REFINE.b

./lib/EB_REFINE.so: EB.BP]MOBJECT/EB_REFINE.so
	CATALOG -L./lib EB.BP EB_REFINE.b

EB.BP]MOBJECT/EB_REFRESH.so: EB.BP/EB_REFRESH.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_REFRESH.b

./lib/EB_REFRESH.so: EB.BP]MOBJECT/EB_REFRESH.so
	CATALOG -L./lib EB.BP EB_REFRESH.b

EB.BP]MOBJECT/EB_REGEX.so: EB.BP/EB_REGEX.b
	BASIC EB.BP EB_REGEX.b

./lib/EB_REGEX.so: EB.BP]MOBJECT/EB_REGEX.so
	CATALOG -L./lib EB.BP EB_REGEX.b

EB.BP]MOBJECT/EB_REPLACE.so: EB.BP/EB_REPLACE.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_REPLACE.b

./lib/EB_REPLACE.so: EB.BP]MOBJECT/EB_REPLACE.so
	CATALOG -L./lib EB.BP EB_REPLACE.b

EB.BP]MOBJECT/EB_ROTATE.so: EB.BP/EB_ROTATE.b
	BASIC EB.BP EB_ROTATE.b

./lib/EB_ROTATE.so: EB.BP]MOBJECT/EB_ROTATE.so
	CATALOG -L./lib EB.BP EB_ROTATE.b

EB.BP]MOBJECT/EB_RSS.so: EB.BP/EB_RSS.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_RSS.b

./lib/EB_RSS.so: EB.BP]MOBJECT/EB_RSS.so
	CATALOG -L./lib EB.BP EB_RSS.b

EB.BP]MOBJECT/EB_SEARCH.so: EB.BP/EB_SEARCH.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/REMOVE.LINE
	BASIC EB.BP EB_SEARCH.b

./lib/EB_SEARCH.so: EB.BP]MOBJECT/EB_SEARCH.so
	CATALOG -L./lib EB.BP EB_SEARCH.b

EB.BP]MOBJECT/EB_SETUPSWITCH.so: EB.BP/EB_SETUPSWITCH.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_SETUPSWITCH.b

./lib/EB_SETUPSWITCH.so: EB.BP]MOBJECT/EB_SETUPSWITCH.so
	CATALOG -L./lib EB.BP EB_SETUPSWITCH.b

EB.BP]MOBJECT/EB_SHOWMEMBERS.so: EB.BP/EB_SHOWMEMBERS.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_SHOWMEMBERS.b

./lib/EB_SHOWMEMBERS.so: EB.BP]MOBJECT/EB_SHOWMEMBERS.so
	CATALOG -L./lib EB.BP EB_SHOWMEMBERS.b

EB.BP]MOBJECT/EB_SWAP.so: EB.BP/EB_SWAP.b
	BASIC EB.BP EB_SWAP.b

./lib/EB_SWAP.so: EB.BP]MOBJECT/EB_SWAP.so
	CATALOG -L./lib EB.BP EB_SWAP.b

EB.BP]MOBJECT/EB_TABCOL.so: EB.BP/EB_TABCOL.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_TABCOL.b

./lib/EB_TABCOL.so: EB.BP]MOBJECT/EB_TABCOL.so
	CATALOG -L./lib EB.BP EB_TABCOL.b

EB.BP]MOBJECT/EB_TABS.so: EB.BP/EB_TABS.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_TABS.b

./lib/EB_TABS.so: EB.BP]MOBJECT/EB_TABS.so
	CATALOG -L./lib EB.BP EB_TABS.b

EB.BP]MOBJECT/EB_TCL.so: EB.BP/EB_TCL.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.CRT.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/ED.STACK EB.OS.INCLUDES/ED.STACK.NOCAP EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.TIMEOUT EB.OS.INCLUDES/OS EB.OS.INCLUDES/TCL.EXEC.CMD EB.OS.INCLUDES/TCL.MERGE EB.OS.INCLUDES/TCL.PARAMS EB.OS.INCLUDES/TIMEOUT.OFF
	BASIC EB.BP EB_TCL.b

./lib/EB_TCL.so: EB.BP]MOBJECT/EB_TCL.so
	CATALOG -L./lib EB.BP EB_TCL.b

EB.BP]MOBJECT/EB_TRIM.so: EB.BP/EB_TRIM.b
	BASIC EB.BP EB_TRIM.b

./lib/EB_TRIM.so: EB.BP]MOBJECT/EB_TRIM.so
	CATALOG -L./lib EB.BP EB_TRIM.b

EB.BP]MOBJECT/EB_UT_BOX.so: EB.BP/EB_UT_BOX.b EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR
	BASIC EB.BP EB_UT_BOX.b

./lib/EB_UT_BOX.so: EB.BP]MOBJECT/EB_UT_BOX.so
	CATALOG -L./lib EB.BP EB_UT_BOX.b

EB.BP]MOBJECT/EB_UT_INIT.so: EB.BP/EB_UT_INIT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.EQUS/TERM.TYPES EB.EQUS/USER_SETTINGS EB.INCLUDES/INPUT.CODES EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS EB.OS.INCLUDES/SKIP.PASSWORD EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/WHO
	BASIC EB.BP EB_UT_INIT.b

./lib/EB_UT_INIT.so: EB.BP]MOBJECT/EB_UT_INIT.so
	CATALOG -L./lib EB.BP EB_UT_INIT.b

EB.BP]MOBJECT/EB_UT_INPUT_ZERO.so: EB.BP/EB_UT_INPUT_ZERO.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/STD.EQUS EB.OS.INCLUDES/CHECK.ACT.SUB EB.OS.INCLUDES/CHECK.SUB.SUB EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.DIFF EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.12 EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_UT_INPUT_ZERO.b

./lib/EB_UT_INPUT_ZERO.so: EB.BP]MOBJECT/EB_UT_INPUT_ZERO.so
	CATALOG -L./lib EB.BP EB_UT_INPUT_ZERO.b

EB.BP]MOBJECT/EB_UT_WP.so: EB.BP/EB_UT_WP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/EB.STD.EQUS EB.INCLUDES/EB.WP.SUBROUTINES EB.OS.INCLUDES/AT.MINUS.CODES EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/DATE.CONV EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.LINE.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/PC.RESET.CURSOR EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/USER.EXITS
	BASIC EB.BP EB_UT_WP.b

./lib/EB_UT_WP.so: EB.BP]MOBJECT/EB_UT_WP.so
	CATALOG -L./lib EB.BP EB_UT_WP.b

EB.BP]MOBJECT/EB_VERSION.so: EB.BP/EB_VERSION.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_VERSION.b

./lib/EB_VERSION.so: EB.BP]MOBJECT/EB_VERSION.so
	CATALOG -L./lib EB.BP EB_VERSION.b

EB.BP]MOBJECT/EB_VERS_CTRL.so: EB.BP/EB_VERS_CTRL.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/GET.HOME EB.INCLUDES/PWD EB.INCLUDES/SRCDBG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_VERS_CTRL.b

./lib/EB_VERS_CTRL.so: EB.BP]MOBJECT/EB_VERS_CTRL.so
	CATALOG -L./lib EB.BP EB_VERS_CTRL.b

EB.BP]MOBJECT/FNKEYTRANS.so: EB.BP/FNKEYTRANS.b
	BASIC EB.BP FNKEYTRANS.b

./lib/FNKEYTRANS.so: EB.BP]MOBJECT/FNKEYTRANS.so
	CATALOG -L./lib EB.BP FNKEYTRANS.b

EB.BP]MOBJECT/GETFLNM.so: EB.BP/GETFLNM.b
	BASIC EB.BP GETFLNM.b

./lib/GETFLNM.so: EB.BP]MOBJECT/GETFLNM.so
	CATALOG -L./lib EB.BP GETFLNM.b

EB.BP]MOBJECT/GETFULLPATH.so: EB.BP/GETFULLPATH.b EB.EQUS/EB.COMMONS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP GETFULLPATH.b

./lib/GETFULLPATH.so: EB.BP]MOBJECT/GETFULLPATH.so
	CATALOG -L./lib EB.BP GETFULLPATH.b

EB.BP]MOBJECT/GETSAME.so: EB.BP/GETSAME.b
	BASIC EB.BP GETSAME.b

./bin/GETSAME: EB.BP]MOBJECT/GETSAME.so
	CATALOG -o./bin EB.BP GETSAME.b

EB.BP]MOBJECT/GETSRCTYPE.so: EB.BP/GETSRCTYPE.b
	BASIC EB.BP GETSRCTYPE.b

./lib/GETSRCTYPE.so: EB.BP]MOBJECT/GETSRCTYPE.so
	CATALOG -L./lib EB.BP GETSRCTYPE.b

EB.BP]MOBJECT/GETYN.so: EB.BP/GETYN.b
	BASIC EB.BP GETYN.b

./lib/GETYN.so: EB.BP]MOBJECT/GETYN.so
	CATALOG -L./lib EB.BP GETYN.b

EB.BP]MOBJECT/GET_CATALOG_FILE.so: EB.BP/GET_CATALOG_FILE.b
	BASIC EB.BP GET_CATALOG_FILE.b

./lib/GET_CATALOG_FILE.so: EB.BP]MOBJECT/GET_CATALOG_FILE.so
	CATALOG -L./lib EB.BP GET_CATALOG_FILE.b

EB.BP]MOBJECT/GET_CATALOG_FILES.so: EB.BP/GET_CATALOG_FILES.b
	BASIC EB.BP GET_CATALOG_FILES.b

./lib/GET_CATALOG_FILES.so: EB.BP]MOBJECT/GET_CATALOG_FILES.so
	CATALOG -L./lib EB.BP GET_CATALOG_FILES.b

EB.BP]MOBJECT/GITCHECKOUT.so: EB.BP/GITCHECKOUT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GITCHECKOUT.b

./bin/GITCHECKOUT: EB.BP]MOBJECT/GITCHECKOUT.so
	CATALOG -o./bin EB.BP GITCHECKOUT.b

EB.BP]MOBJECT/GITCOMMIT.so: EB.BP/GITCOMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GITCOMMIT.b

./bin/GITCOMMIT: EB.BP]MOBJECT/GITCOMMIT.so
	CATALOG -o./bin EB.BP GITCOMMIT.b

EB.BP]MOBJECT/GITDELETE.so: EB.BP/GITDELETE.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GITDELETE.b

./bin/GITDELETE: EB.BP]MOBJECT/GITDELETE.so
	CATALOG -o./bin EB.BP GITDELETE.b

EB.BP]MOBJECT/GITRENAME.so: EB.BP/GITRENAME.b
	BASIC EB.BP GITRENAME.b

./bin/GITRENAME: EB.BP]MOBJECT/GITRENAME.so
	CATALOG -o./bin EB.BP GITRENAME.b

EB.BP]MOBJECT/GITREVERT.so: EB.BP/GITREVERT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GITREVERT.b

./bin/GITREVERT: EB.BP]MOBJECT/GITREVERT.so
	CATALOG -o./bin EB.BP GITREVERT.b

EB.BP]MOBJECT/GITSELECT.so: EB.BP/GITSELECT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GITSELECT.b

./bin/GITSELECT: EB.BP]MOBJECT/GITSELECT.so
	CATALOG -o./bin EB.BP GITSELECT.b

EB.BP]MOBJECT/GIT_ADD.so: EB.BP/GIT_ADD.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_ADD.b

./lib/GIT_ADD.so: EB.BP]MOBJECT/GIT_ADD.so
	CATALOG -L./lib EB.BP GIT_ADD.b

EB.BP]MOBJECT/GIT_CHECKIN.so: EB.BP/GIT_CHECKIN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_CHECKIN.b

./lib/GIT_CHECKIN.so: EB.BP]MOBJECT/GIT_CHECKIN.so
	CATALOG -L./lib EB.BP GIT_CHECKIN.b

EB.BP]MOBJECT/GIT_CHECKOUT.so: EB.BP/GIT_CHECKOUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP GIT_CHECKOUT.b

./lib/GIT_CHECKOUT.so: EB.BP]MOBJECT/GIT_CHECKOUT.so
	CATALOG -L./lib EB.BP GIT_CHECKOUT.b

EB.BP]MOBJECT/GIT_CLEAN.so: EB.BP/GIT_CLEAN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_CLEAN.b

./lib/GIT_CLEAN.so: EB.BP]MOBJECT/GIT_CLEAN.so
	CATALOG -L./lib EB.BP GIT_CLEAN.b

EB.BP]MOBJECT/GIT_COMMIT.so: EB.BP/GIT_COMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_COMMIT.b

./lib/GIT_COMMIT.so: EB.BP]MOBJECT/GIT_COMMIT.so
	CATALOG -L./lib EB.BP GIT_COMMIT.b

EB.BP]MOBJECT/GIT_DELETE.so: EB.BP/GIT_DELETE.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_DELETE.b

./lib/GIT_DELETE.so: EB.BP]MOBJECT/GIT_DELETE.so
	CATALOG -L./lib EB.BP GIT_DELETE.b

EB.BP]MOBJECT/GIT_EXEC.so: EB.BP/GIT_EXEC.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_EXEC.b

./lib/GIT_EXEC.so: EB.BP]MOBJECT/GIT_EXEC.so
	CATALOG -L./lib EB.BP GIT_EXEC.b

EB.BP]MOBJECT/GIT_GETCATLID.so: EB.BP/GIT_GETCATLID.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/SRCDBG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP GIT_GETCATLID.b

./lib/GIT_GETCATLID.so: EB.BP]MOBJECT/GIT_GETCATLID.so
	CATALOG -L./lib EB.BP GIT_GETCATLID.b

EB.BP]MOBJECT/GIT_GETHOMEPATH.so: EB.BP/GIT_GETHOMEPATH.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_GETHOMEPATH.b

./lib/GIT_GETHOMEPATH.so: EB.BP]MOBJECT/GIT_GETHOMEPATH.so
	CATALOG -L./lib EB.BP GIT_GETHOMEPATH.b

EB.BP]MOBJECT/GIT_GETORIGPATH.so: EB.BP/GIT_GETORIGPATH.b
	BASIC EB.BP GIT_GETORIGPATH.b

./lib/GIT_GETORIGPATH.so: EB.BP]MOBJECT/GIT_GETORIGPATH.so
	CATALOG -L./lib EB.BP GIT_GETORIGPATH.b

EB.BP]MOBJECT/GIT_GETPWD.so: EB.BP/GIT_GETPWD.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_GETPWD.b

./lib/GIT_GETPWD.so: EB.BP]MOBJECT/GIT_GETPWD.so
	CATALOG -L./lib EB.BP GIT_GETPWD.b

EB.BP]MOBJECT/GIT_GETROOT.so: EB.BP/GIT_GETROOT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_GETROOT.b

./lib/GIT_GETROOT.so: EB.BP]MOBJECT/GIT_GETROOT.so
	CATALOG -L./lib EB.BP GIT_GETROOT.b

EB.BP]MOBJECT/GIT_GET_REPOSITORY.so: EB.BP/GIT_GET_REPOSITORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_GET_REPOSITORY.b

./lib/GIT_GET_REPOSITORY.so: EB.BP]MOBJECT/GIT_GET_REPOSITORY.so
	CATALOG -L./lib EB.BP GIT_GET_REPOSITORY.b

EB.BP]MOBJECT/GIT_HISTORY.so: EB.BP/GIT_HISTORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_HISTORY.b

./lib/GIT_HISTORY.so: EB.BP]MOBJECT/GIT_HISTORY.so
	CATALOG -L./lib EB.BP GIT_HISTORY.b

EB.BP]MOBJECT/GIT_READ.so: EB.BP/GIT_READ.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP GIT_READ.b

./lib/GIT_READ.so: EB.BP]MOBJECT/GIT_READ.so
	CATALOG -L./lib EB.BP GIT_READ.b

EB.BP]MOBJECT/GIT_REPOSITORY.so: EB.BP/GIT_REPOSITORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_REPOSITORY.b

./lib/GIT_REPOSITORY.so: EB.BP]MOBJECT/GIT_REPOSITORY.so
	CATALOG -L./lib EB.BP GIT_REPOSITORY.b

EB.BP]MOBJECT/GIT_REVERT.so: EB.BP/GIT_REVERT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_REVERT.b

./lib/GIT_REVERT.so: EB.BP]MOBJECT/GIT_REVERT.so
	CATALOG -L./lib EB.BP GIT_REVERT.b

EB.BP]MOBJECT/GIT_SRC_STATUS.so: EB.BP/GIT_SRC_STATUS.b EB.INCLUDES/SRCDBG
	BASIC EB.BP GIT_SRC_STATUS.b

./lib/GIT_SRC_STATUS.so: EB.BP]MOBJECT/GIT_SRC_STATUS.so
	CATALOG -L./lib EB.BP GIT_SRC_STATUS.b

EB.BP]MOBJECT/GIT_SYNC.so: EB.BP/GIT_SYNC.b
	BASIC EB.BP GIT_SYNC.b

./lib/GIT_SYNC.so: EB.BP]MOBJECT/GIT_SYNC.so
	CATALOG -L./lib EB.BP GIT_SYNC.b

EB.BP]MOBJECT/JBCUserConversions.so: EB.BP/JBCUserConversions.b
	BASIC EB.BP JBCUserConversions.b

./lib/JBCUserConversions.so: EB.BP]MOBJECT/JBCUserConversions.so
	CATALOG -L./lib EB.BP JBCUserConversions.b

EB.BP]MOBJECT/LASTEB.so: EB.BP/LASTEB.b
	BASIC EB.BP LASTEB.b

./bin/LASTEB: EB.BP]MOBJECT/LASTEB.so
	CATALOG -o./bin EB.BP LASTEB.b

EB.BP]MOBJECT/SPLITFILEPATH.so: EB.BP/SPLITFILEPATH.b
	BASIC EB.BP SPLITFILEPATH.b

./lib/SPLITFILEPATH.so: EB.BP]MOBJECT/SPLITFILEPATH.so
	CATALOG -L./lib EB.BP SPLITFILEPATH.b

EB.BP]MOBJECT/SRCCHECKOUT.so: EB.BP/SRCCHECKOUT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SRCCHECKOUT.b

./bin/SRCCHECKOUT: EB.BP]MOBJECT/SRCCHECKOUT.so
	CATALOG -o./bin EB.BP SRCCHECKOUT.b

EB.BP]MOBJECT/SRCCOMMIT.so: EB.BP/SRCCOMMIT.b
	BASIC EB.BP SRCCOMMIT.b

./bin/SRCCOMMIT: EB.BP]MOBJECT/SRCCOMMIT.so
	CATALOG -o./bin EB.BP SRCCOMMIT.b

EB.BP]MOBJECT/SRCDELETE.so: EB.BP/SRCDELETE.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SRCDELETE.b

./bin/SRCDELETE: EB.BP]MOBJECT/SRCDELETE.so
	CATALOG -o./bin EB.BP SRCDELETE.b

EB.BP]MOBJECT/SRCPUSH.so: EB.BP/SRCPUSH.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SRCPUSH.b

./lib/SRCPUSH.so: EB.BP]MOBJECT/SRCPUSH.so
	CATALOG -L./lib EB.BP SRCPUSH.b

EB.BP]MOBJECT/SRCRENAME.so: EB.BP/SRCRENAME.b
	BASIC EB.BP SRCRENAME.b

./bin/SRCRENAME: EB.BP]MOBJECT/SRCRENAME.so
	CATALOG -o./bin EB.BP SRCRENAME.b

EB.BP]MOBJECT/SRCREVERT.so: EB.BP/SRCREVERT.b
	BASIC EB.BP SRCREVERT.b

./bin/SRCREVERT: EB.BP]MOBJECT/SRCREVERT.so
	CATALOG -o./bin EB.BP SRCREVERT.b

EB.BP]MOBJECT/SRCSELECT.so: EB.BP/SRCSELECT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SRCSELECT.b

./bin/SRCSELECT: EB.BP]MOBJECT/SRCSELECT.so
	CATALOG -o./bin EB.BP SRCSELECT.b

EB.BP]MOBJECT/SRC_ADD.so: EB.BP/SRC_ADD.b
	BASIC EB.BP SRC_ADD.b

./lib/SRC_ADD.so: EB.BP]MOBJECT/SRC_ADD.so
	CATALOG -L./lib EB.BP SRC_ADD.b

EB.BP]MOBJECT/SRC_CASE.so: EB.BP/SRC_CASE.b
	BASIC EB.BP SRC_CASE.b

./lib/SRC_CASE.so: EB.BP]MOBJECT/SRC_CASE.so
	CATALOG -L./lib EB.BP SRC_CASE.b

EB.BP]MOBJECT/SRC_CHECKIN.so: EB.BP/SRC_CHECKIN.b
	BASIC EB.BP SRC_CHECKIN.b

./lib/SRC_CHECKIN.so: EB.BP]MOBJECT/SRC_CHECKIN.so
	CATALOG -L./lib EB.BP SRC_CHECKIN.b

EB.BP]MOBJECT/SRC_CHECKOUT.so: EB.BP/SRC_CHECKOUT.b
	BASIC EB.BP SRC_CHECKOUT.b

./lib/SRC_CHECKOUT.so: EB.BP]MOBJECT/SRC_CHECKOUT.so
	CATALOG -L./lib EB.BP SRC_CHECKOUT.b

EB.BP]MOBJECT/SRC_CLEAN.so: EB.BP/SRC_CLEAN.b
	BASIC EB.BP SRC_CLEAN.b

./lib/SRC_CLEAN.so: EB.BP]MOBJECT/SRC_CLEAN.so
	CATALOG -L./lib EB.BP SRC_CLEAN.b

EB.BP]MOBJECT/SRC_COMMIT.so: EB.BP/SRC_COMMIT.b
	BASIC EB.BP SRC_COMMIT.b

./lib/SRC_COMMIT.so: EB.BP]MOBJECT/SRC_COMMIT.so
	CATALOG -L./lib EB.BP SRC_COMMIT.b

EB.BP]MOBJECT/SRC_DELETE.so: EB.BP/SRC_DELETE.b
	BASIC EB.BP SRC_DELETE.b

./lib/SRC_DELETE.so: EB.BP]MOBJECT/SRC_DELETE.so
	CATALOG -L./lib EB.BP SRC_DELETE.b

EB.BP]MOBJECT/SRC_EXEC.so: EB.BP/SRC_EXEC.b
	BASIC EB.BP SRC_EXEC.b

./lib/SRC_EXEC.so: EB.BP]MOBJECT/SRC_EXEC.so
	CATALOG -L./lib EB.BP SRC_EXEC.b

EB.BP]MOBJECT/SRC_GETCATLID.so: EB.BP/SRC_GETCATLID.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_GETCATLID.b

./lib/SRC_GETCATLID.so: EB.BP]MOBJECT/SRC_GETCATLID.so
	CATALOG -L./lib EB.BP SRC_GETCATLID.b

EB.BP]MOBJECT/SRC_GETHOMEPATH.so: EB.BP/SRC_GETHOMEPATH.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_GETHOMEPATH.b

./lib/SRC_GETHOMEPATH.so: EB.BP]MOBJECT/SRC_GETHOMEPATH.so
	CATALOG -L./lib EB.BP SRC_GETHOMEPATH.b

EB.BP]MOBJECT/SRC_GETORIGPATH.so: EB.BP/SRC_GETORIGPATH.b
	BASIC EB.BP SRC_GETORIGPATH.b

./lib/SRC_GETORIGPATH.so: EB.BP]MOBJECT/SRC_GETORIGPATH.so
	CATALOG -L./lib EB.BP SRC_GETORIGPATH.b

EB.BP]MOBJECT/SRC_GETPWD.so: EB.BP/SRC_GETPWD.b
	BASIC EB.BP SRC_GETPWD.b

./lib/SRC_GETPWD.so: EB.BP]MOBJECT/SRC_GETPWD.so
	CATALOG -L./lib EB.BP SRC_GETPWD.b

EB.BP]MOBJECT/SRC_GETROOT.so: EB.BP/SRC_GETROOT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_GETROOT.b

./lib/SRC_GETROOT.so: EB.BP]MOBJECT/SRC_GETROOT.so
	CATALOG -L./lib EB.BP SRC_GETROOT.b

EB.BP]MOBJECT/SRC_GET_REPOSITORY.so: EB.BP/SRC_GET_REPOSITORY.b
	BASIC EB.BP SRC_GET_REPOSITORY.b

./lib/SRC_GET_REPOSITORY.so: EB.BP]MOBJECT/SRC_GET_REPOSITORY.so
	CATALOG -L./lib EB.BP SRC_GET_REPOSITORY.b

EB.BP]MOBJECT/SRC_HISTORY.so: EB.BP/SRC_HISTORY.b
	BASIC EB.BP SRC_HISTORY.b

./lib/SRC_HISTORY.so: EB.BP]MOBJECT/SRC_HISTORY.so
	CATALOG -L./lib EB.BP SRC_HISTORY.b

EB.BP]MOBJECT/SRC_OPENHIST.so: EB.BP/SRC_OPENHIST.b
	BASIC EB.BP SRC_OPENHIST.b

./lib/SRC_OPENHIST.so: EB.BP]MOBJECT/SRC_OPENHIST.so
	CATALOG -L./lib EB.BP SRC_OPENHIST.b

EB.BP]MOBJECT/SRC_OPENLOCKS.so: EB.BP/SRC_OPENLOCKS.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP SRC_OPENLOCKS.b

./lib/SRC_OPENLOCKS.so: EB.BP]MOBJECT/SRC_OPENLOCKS.so
	CATALOG -L./lib EB.BP SRC_OPENLOCKS.b

EB.BP]MOBJECT/SRC_READ.so: EB.BP/SRC_READ.b
	BASIC EB.BP SRC_READ.b

./lib/SRC_READ.so: EB.BP]MOBJECT/SRC_READ.so
	CATALOG -L./lib EB.BP SRC_READ.b

EB.BP]MOBJECT/SRC_READHIST.so: EB.BP/SRC_READHIST.b EB.INCLUDES/GET.USER EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_READHIST.b

./lib/SRC_READHIST.so: EB.BP]MOBJECT/SRC_READHIST.so
	CATALOG -L./lib EB.BP SRC_READHIST.b

EB.BP]MOBJECT/SRC_REMOVEHIST.so: EB.BP/SRC_REMOVEHIST.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_REMOVEHIST.b

./lib/SRC_REMOVEHIST.so: EB.BP]MOBJECT/SRC_REMOVEHIST.so
	CATALOG -L./lib EB.BP SRC_REMOVEHIST.b

EB.BP]MOBJECT/SRC_REPOSITORY.so: EB.BP/SRC_REPOSITORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_REPOSITORY.b

./lib/SRC_REPOSITORY.so: EB.BP]MOBJECT/SRC_REPOSITORY.so
	CATALOG -L./lib EB.BP SRC_REPOSITORY.b

EB.BP]MOBJECT/SRC_REVERT.so: EB.BP/SRC_REVERT.b
	BASIC EB.BP SRC_REVERT.b

./lib/SRC_REVERT.so: EB.BP]MOBJECT/SRC_REVERT.so
	CATALOG -L./lib EB.BP SRC_REVERT.b

EB.BP]MOBJECT/SRC_SENTENCE.so: EB.BP/SRC_SENTENCE.b EB.INCLUDES/DISPLAY.SYNTAX EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_SENTENCE.b

./lib/SRC_SENTENCE.so: EB.BP]MOBJECT/SRC_SENTENCE.so
	CATALOG -L./lib EB.BP SRC_SENTENCE.b

EB.BP]MOBJECT/SRC_SRC_STATUS.so: EB.BP/SRC_SRC_STATUS.b
	BASIC EB.BP SRC_SRC_STATUS.b

./lib/SRC_SRC_STATUS.so: EB.BP]MOBJECT/SRC_SRC_STATUS.so
	CATALOG -L./lib EB.BP SRC_SRC_STATUS.b

EB.BP]MOBJECT/SRC_SYNC.so: EB.BP/SRC_SYNC.b
	BASIC EB.BP SRC_SYNC.b

./lib/SRC_SYNC.so: EB.BP]MOBJECT/SRC_SYNC.so
	CATALOG -L./lib EB.BP SRC_SYNC.b

EB.BP]MOBJECT/SRC_UPDATEHIST.so: EB.BP/SRC_UPDATEHIST.b EB.INCLUDES/GET.USER EB.INCLUDES/SRCDBG
	BASIC EB.BP SRC_UPDATEHIST.b

./lib/SRC_UPDATEHIST.so: EB.BP]MOBJECT/SRC_UPDATEHIST.so
	CATALOG -L./lib EB.BP SRC_UPDATEHIST.b

EB.BP]MOBJECT/SVNCHECKOUT.so: EB.BP/SVNCHECKOUT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVNCHECKOUT.b

./bin/SVNCHECKOUT: EB.BP]MOBJECT/SVNCHECKOUT.so
	CATALOG -o./bin EB.BP SVNCHECKOUT.b

EB.BP]MOBJECT/SVNCOMMIT.so: EB.BP/SVNCOMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVNCOMMIT.b

./bin/SVNCOMMIT: EB.BP]MOBJECT/SVNCOMMIT.so
	CATALOG -o./bin EB.BP SVNCOMMIT.b

EB.BP]MOBJECT/SVNDELETE.so: EB.BP/SVNDELETE.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVNDELETE.b

./bin/SVNDELETE: EB.BP]MOBJECT/SVNDELETE.so
	CATALOG -o./bin EB.BP SVNDELETE.b

EB.BP]MOBJECT/SVNRENAME.so: EB.BP/SVNRENAME.b
	BASIC EB.BP SVNRENAME.b

./bin/SVNRENAME: EB.BP]MOBJECT/SVNRENAME.so
	CATALOG -o./bin EB.BP SVNRENAME.b

EB.BP]MOBJECT/SVNREVERT.so: EB.BP/SVNREVERT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVNREVERT.b

./bin/SVNREVERT: EB.BP]MOBJECT/SVNREVERT.so
	CATALOG -o./bin EB.BP SVNREVERT.b

EB.BP]MOBJECT/SVNSELECT.so: EB.BP/SVNSELECT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVNSELECT.b

./bin/SVNSELECT: EB.BP]MOBJECT/SVNSELECT.so
	CATALOG -o./bin EB.BP SVNSELECT.b

EB.BP]MOBJECT/SVN_ADD.so: EB.BP/SVN_ADD.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_ADD.b

./lib/SVN_ADD.so: EB.BP]MOBJECT/SVN_ADD.so
	CATALOG -L./lib EB.BP SVN_ADD.b

EB.BP]MOBJECT/SVN_CHECKIN.so: EB.BP/SVN_CHECKIN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_CHECKIN.b

./lib/SVN_CHECKIN.so: EB.BP]MOBJECT/SVN_CHECKIN.so
	CATALOG -L./lib EB.BP SVN_CHECKIN.b

EB.BP]MOBJECT/SVN_CHECKOUT.so: EB.BP/SVN_CHECKOUT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_CHECKOUT.b

./lib/SVN_CHECKOUT.so: EB.BP]MOBJECT/SVN_CHECKOUT.so
	CATALOG -L./lib EB.BP SVN_CHECKOUT.b

EB.BP]MOBJECT/SVN_CLEAN.so: EB.BP/SVN_CLEAN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_CLEAN.b

./lib/SVN_CLEAN.so: EB.BP]MOBJECT/SVN_CLEAN.so
	CATALOG -L./lib EB.BP SVN_CLEAN.b

EB.BP]MOBJECT/SVN_COMMIT.so: EB.BP/SVN_COMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_COMMIT.b

./lib/SVN_COMMIT.so: EB.BP]MOBJECT/SVN_COMMIT.so
	CATALOG -L./lib EB.BP SVN_COMMIT.b

EB.BP]MOBJECT/SVN_DELETE.so: EB.BP/SVN_DELETE.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_DELETE.b

./lib/SVN_DELETE.so: EB.BP]MOBJECT/SVN_DELETE.so
	CATALOG -L./lib EB.BP SVN_DELETE.b

EB.BP]MOBJECT/SVN_EXEC.so: EB.BP/SVN_EXEC.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_EXEC.b

./lib/SVN_EXEC.so: EB.BP]MOBJECT/SVN_EXEC.so
	CATALOG -L./lib EB.BP SVN_EXEC.b

EB.BP]MOBJECT/SVN_GETCATLID.so: EB.BP/SVN_GETCATLID.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_GETCATLID.b

./lib/SVN_GETCATLID.so: EB.BP]MOBJECT/SVN_GETCATLID.so
	CATALOG -L./lib EB.BP SVN_GETCATLID.b

EB.BP]MOBJECT/SVN_GETHOMEPATH.so: EB.BP/SVN_GETHOMEPATH.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_GETHOMEPATH.b

./lib/SVN_GETHOMEPATH.so: EB.BP]MOBJECT/SVN_GETHOMEPATH.so
	CATALOG -L./lib EB.BP SVN_GETHOMEPATH.b

EB.BP]MOBJECT/SVN_GETORIGPATH.so: EB.BP/SVN_GETORIGPATH.b
	BASIC EB.BP SVN_GETORIGPATH.b

./lib/SVN_GETORIGPATH.so: EB.BP]MOBJECT/SVN_GETORIGPATH.so
	CATALOG -L./lib EB.BP SVN_GETORIGPATH.b

EB.BP]MOBJECT/SVN_GETPWD.so: EB.BP/SVN_GETPWD.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_GETPWD.b

./lib/SVN_GETPWD.so: EB.BP]MOBJECT/SVN_GETPWD.so
	CATALOG -L./lib EB.BP SVN_GETPWD.b

EB.BP]MOBJECT/SVN_GETROOT.so: EB.BP/SVN_GETROOT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_GETROOT.b

./lib/SVN_GETROOT.so: EB.BP]MOBJECT/SVN_GETROOT.so
	CATALOG -L./lib EB.BP SVN_GETROOT.b

EB.BP]MOBJECT/SVN_GET_REPOSITORY.so: EB.BP/SVN_GET_REPOSITORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_GET_REPOSITORY.b

./lib/SVN_GET_REPOSITORY.so: EB.BP]MOBJECT/SVN_GET_REPOSITORY.so
	CATALOG -L./lib EB.BP SVN_GET_REPOSITORY.b

EB.BP]MOBJECT/SVN_HISTORY.so: EB.BP/SVN_HISTORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_HISTORY.b

./lib/SVN_HISTORY.so: EB.BP]MOBJECT/SVN_HISTORY.so
	CATALOG -L./lib EB.BP SVN_HISTORY.b

EB.BP]MOBJECT/SVN_READ.so: EB.BP/SVN_READ.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_READ.b

./lib/SVN_READ.so: EB.BP]MOBJECT/SVN_READ.so
	CATALOG -L./lib EB.BP SVN_READ.b

EB.BP]MOBJECT/SVN_REPOSITORY.so: EB.BP/SVN_REPOSITORY.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_REPOSITORY.b

./lib/SVN_REPOSITORY.so: EB.BP]MOBJECT/SVN_REPOSITORY.so
	CATALOG -L./lib EB.BP SVN_REPOSITORY.b

EB.BP]MOBJECT/SVN_REVERT.so: EB.BP/SVN_REVERT.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_REVERT.b

./lib/SVN_REVERT.so: EB.BP]MOBJECT/SVN_REVERT.so
	CATALOG -L./lib EB.BP SVN_REVERT.b

EB.BP]MOBJECT/SVN_SRC_STATUS.so: EB.BP/SVN_SRC_STATUS.b EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_SRC_STATUS.b

./lib/SVN_SRC_STATUS.so: EB.BP]MOBJECT/SVN_SRC_STATUS.so
	CATALOG -L./lib EB.BP SVN_SRC_STATUS.b

EB.BP]MOBJECT/SVN_SYNC.so: EB.BP/SVN_SYNC.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRCDBG
	BASIC EB.BP SVN_SYNC.b

./lib/SVN_SYNC.so: EB.BP]MOBJECT/SVN_SYNC.so
	CATALOG -L./lib EB.BP SVN_SYNC.b

EB.BP]MOBJECT/UNCOMPILED.so: EB.BP/UNCOMPILED.b
	BASIC EB.BP UNCOMPILED.b

./bin/UNCOMPILED: EB.BP]MOBJECT/UNCOMPILED.so
	CATALOG -o./bin EB.BP UNCOMPILED.b

EB.BP]MOBJECT/color.so: EB.BP/color.b
	BASIC EB.BP color.b

./bin/color: EB.BP]MOBJECT/color.so
	CATALOG -o./bin EB.BP color.b

EB.BP]MOBJECT/initColors.so: EB.BP/initColors.b EB.EQUS/COLOURS EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP initColors.b

./lib/initColors.so: EB.BP]MOBJECT/initColors.so
	CATALOG -L./lib EB.BP initColors.b

EB.BP]MOBJECT/isComment.so: EB.BP/isComment.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isComment.b

./lib/isComment.so: EB.BP]MOBJECT/isComment.so
	CATALOG -L./lib EB.BP isComment.b

EB.BP]MOBJECT/isNumber.so: EB.BP/isNumber.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isNumber.b

./lib/isNumber.so: EB.BP]MOBJECT/isNumber.so
	CATALOG -L./lib EB.BP isNumber.b

EB.BP]MOBJECT/isReservedWord.so: EB.BP/isReservedWord.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isReservedWord.b

./lib/isReservedWord.so: EB.BP]MOBJECT/isReservedWord.so
	CATALOG -L./lib EB.BP isReservedWord.b

EB.BP]MOBJECT/isSeparator.so: EB.BP/isSeparator.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isSeparator.b

./lib/isSeparator.so: EB.BP]MOBJECT/isSeparator.so
	CATALOG -L./lib EB.BP isSeparator.b

EB.BP]MOBJECT/isSpacer.so: EB.BP/isSpacer.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isSpacer.b

./lib/isSpacer.so: EB.BP]MOBJECT/isSpacer.so
	CATALOG -L./lib EB.BP isSpacer.b

EB.BP]MOBJECT/isString.so: EB.BP/isString.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isString.b

./lib/isString.so: EB.BP]MOBJECT/isString.so
	CATALOG -L./lib EB.BP isString.b

EB.BP]MOBJECT/jEDIfmt.so: EB.BP/jEDIfmt.b
	BASIC EB.BP jEDIfmt.b

./bin/jEDIfmt: EB.BP]MOBJECT/jEDIfmt.so
	CATALOG -o./bin EB.BP jEDIfmt.b

EB.BP]MOBJECT/lexLine.so: EB.BP/lexLine.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP lexLine.b

./lib/lexLine.so: EB.BP]MOBJECT/lexLine.so
	CATALOG -L./lib EB.BP lexLine.b

EB.BP]MOBJECT/lexTest.so: EB.BP/lexTest.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP lexTest.b

./bin/lexTest: EB.BP]MOBJECT/lexTest.so
	CATALOG -o./bin EB.BP lexTest.b

EB.BP]MOBJECT/nextToken.so: EB.BP/nextToken.b EB.INCLUDES/lexCharTypes.h
	BASIC EB.BP nextToken.b

./lib/nextToken.so: EB.BP]MOBJECT/nextToken.so
	CATALOG -L./lib EB.BP nextToken.b

EB.BP]MOBJECT/stringType.so: EB.BP/stringType.b EB.INCLUDES/lexEquates.h
	BASIC EB.BP stringType.b

./lib/stringType.so: EB.BP]MOBJECT/stringType.so
	CATALOG -L./lib EB.BP stringType.b

EB.BP]MOBJECT/ttvt220_TRANS.so: EB.BP/ttvt220_TRANS.b
	BASIC EB.BP ttvt220_TRANS.b

./lib/ttvt220_TRANS.so: EB.BP]MOBJECT/ttvt220_TRANS.so
	CATALOG -L./lib EB.BP ttvt220_TRANS.b


rebuild: $(libobjs) $(binobjs)
	CATALOG -o./bin EB.BP COMPARE_ITEM.b COMPL.b COMPL2.b CONVF2DIR.b D3BASIC.b EB.b EBCRT.b EBFIND.b EBKEYS.b EBKEYTEST.b EBL.b EBTTCOPY.b EBV.b EB_BGCOMPILE.b EB_ENABLE.b GETSAME.b GITCHECKOUT.b GITCOMMIT.b GITDELETE.b GITRENAME.b
	CATALOG -o./bin EB.BP GITREVERT.b GITSELECT.b LASTEB.b SRCCHECKOUT.b SRCCOMMIT.b SRCDELETE.b SRCRENAME.b SRCREVERT.b SRCSELECT.b SVNCHECKOUT.b SVNCOMMIT.b SVNDELETE.b SVNRENAME.b SVNREVERT.b SVNSELECT.b UNCOMPILED.b color.b jEDIfmt.b lexTest.b

clean:
	-rm -rf ./lib/*
	-rm -f ./bin/*
	-rm -f ./EB.BP]MOBJECT/*
