libobjs=EB.BP]MOBJECT/\$$SVN_COMMIT EB.BP]MOBJECT/\$$SVN_SUBVERSION EB.BP]MOBJECT/EB_REFINE.o EB.BP]MOBJECT/EB_ROTATE.o EB.BP]MOBJECT/\$$SVN_CHECKIN EB.BP]MOBJECT/EB_TABCOL.o EB.BP]MOBJECT/SPLITFILEPATH.o EB.BP]MOBJECT/\$$SVN_CHECKOUT EB.BP]MOBJECT/\$$SVN_GET_REPOSITORY EB.BP]MOBJECT/EB_SHOWMEMBERS.o EB.BP]MOBJECT/EB_ANCHAR.o EB.BP]MOBJECT/EB_UT_BOX.o EB.BP]MOBJECT/EB_GETRPL.o EB.BP]MOBJECT/EB_MOVE.o EB.BP]MOBJECT/\$$GETFLNM EB.BP]MOBJECT/lexLine.o EB.BP]MOBJECT/EBGETKEY.o EB.BP]MOBJECT/EB_BOX.o EB.BP]MOBJECT/\$$EB_CH.COLOUR EB.BP]MOBJECT/EB_EREPLACE.o EB.BP]MOBJECT/initColors.o EB.BP]MOBJECT/EB_TABS.o EB.BP]MOBJECT/\$$SVN_CASE EB.BP]MOBJECT/\$$SVN_GETPWD EB.BP]MOBJECT/EB_VERSION.o EB.BP]MOBJECT/\$$SVN_GETROOT EB.BP]MOBJECT/\$$SVN_HISTORY EB.BP]MOBJECT/EB_FILE.o EB.BP]MOBJECT/EB_TCL.o EB.BP]MOBJECT/SVN_READ.o EB.BP]MOBJECT/EB_ADD.o EB.BP]MOBJECT/EB_EXPANDFLNM.o EB.BP]MOBJECT/EB_GETTCC.o EB.BP]MOBJECT/EB_MERGE.o EB.BP]MOBJECT/EB_READHEADERS.o EB.BP]MOBJECT/\$$GET_CATALOG_FILES EB.BP]MOBJECT/\$$SVN_UPDATEHIST EB.BP]MOBJECT/EB_HELP.o EB.BP]MOBJECT/EB_INP.o EB.BP]MOBJECT/EB_FINDDEC.o EB.BP]MOBJECT/EB_REPLACE.o EB.BP]MOBJECT/EB_VERS_CTRL.o EB.BP]MOBJECT/EB_CLOSE.o EB.BP]MOBJECT/EB_CONVCODE.o EB.BP]MOBJECT/EB_SWAP.o EB.BP]MOBJECT/EB_GETMOUSE.o EB.BP]MOBJECT/\$$SVN_DELETE EB.BP]MOBJECT/EB_PASTE.o EB.BP]MOBJECT/\$$SVN_CLEAN EB.BP]MOBJECT/\$$SVN_OPENHIST EB.BP]MOBJECT/EB_ERRMSG.o EB.BP]MOBJECT/\$$SVN_SRC_STATUS EB.BP]MOBJECT/EBJSHOW.o EB.BP]MOBJECT/EB_SETUPSWITCH.o EB.BP]MOBJECT/EB_OPEN.o EB.BP]MOBJECT/EB_UT_INIT.o EB.BP]MOBJECT/\$$SVN_REVERT EB.BP]MOBJECT/EB_AUTOSAVE.o EB.BP]MOBJECT/EB_CHOICES.o EB.BP]MOBJECT/EB_READINCL.o EB.BP]MOBJECT/\$$SVN_GETCATLID EB.BP]MOBJECT/isComment.o EB.BP]MOBJECT/stringType.o EB.BP]MOBJECT/EB_MAKEHIST.o EB.BP]MOBJECT/EB_CUT.o EB.BP]MOBJECT/EB_REFRESH.o EB.BP]MOBJECT/EB_SEARCH.o EB.BP]MOBJECT/EB_UT_INPUT_ZERO.o EB.BP]MOBJECT/\$$SVN_EXEC EB.BP]MOBJECT/\$$SVN_GETHOMEPATH EB.BP]MOBJECT/\$$GETFULLPATH EB.BP]MOBJECT/JBCUserConversions.o EB.BP]MOBJECT/\$$GETYN EB.BP]MOBJECT/EB_GET_INPUT.o EB.BP]MOBJECT/EB_RSS.o EB.BP]MOBJECT/\$$GET_CATALOG_FILE EB.BP]MOBJECT/EB_PRINT.o EB.BP]MOBJECT/\$$SVN_ADD EB.BP]MOBJECT/isSeparator.o EB.BP]MOBJECT/isString.o EB.BP]MOBJECT/EB_INPUT_ZERO.o EB.BP]MOBJECT/\$$SVN_REMOVEHIST EB.BP]MOBJECT/nextToken.o EB.BP]MOBJECT/EB_TRIM.o EB.BP]MOBJECT/\$$SVN_GETORIGPATH EB.BP]MOBJECT/ttvt220_TRANS.o EB.BP]MOBJECT/EB_ASSIGN_OPEN.o EB.BP]MOBJECT/\$$GET.FILE.STAMP EB.BP]MOBJECT/\$$SVN_READHIST EB.BP]MOBJECT/\$$SVN_SENTENCE EB.BP]MOBJECT/EB_INPUT.o EB.BP]MOBJECT/EB_FIND.o EB.BP]MOBJECT/EB_MERRMSG.o EB.BP]MOBJECT/EB_FORMAT.o EB.BP]MOBJECT/EB_OPEN_FILE.o EB.BP]MOBJECT/EB_REGEX.o EB.BP]MOBJECT/\$$SVN_SYNC EB.BP]MOBJECT/isNumber.o EB.BP]MOBJECT/isReservedWord.o EB.BP]MOBJECT/EB_COMPARE.o EB.BP]MOBJECT/EB_GIT.o EB.BP]MOBJECT/EBGETHOME.o EB.BP]MOBJECT/FNKEYTRANS.o EB.BP]MOBJECT/\$$SVN_OPENLOCKS EB.BP]MOBJECT/EB_MARKADJ.o EB.BP]MOBJECT/EB_UT_WP.o EB.BP]MOBJECT/isSpacer.o
binobjs=EB.BP]MOBJECT/EBL.o EB.BP]MOBJECT/EBCRT.o EB.BP]MOBJECT/UNCOMPILED.o EB.BP]MOBJECT/$$SVNCOMMIT EB.BP]MOBJECT/$$SVNSELECT EB.BP]MOBJECT/CONVF2DIR.o EB.BP]MOBJECT/color.o EB.BP]MOBJECT/$$SVNCHECKOUT EB.BP]MOBJECT/$$SVNDELETE EB.BP]MOBJECT/EBKEYS.o EB.BP]MOBJECT/EB_ENABLE.o EB.BP]MOBJECT/lex.o EB.BP]MOBJECT/$$SVNRENAME EB.BP]MOBJECT/D3BASIC.o EB.BP]MOBJECT/COMPARE_ITEM.o EB.BP]MOBJECT/COMPL.o EB.BP]MOBJECT/EB.o EB.BP]MOBJECT/GETSAME.o EB.BP]MOBJECT/EBV.o EB.BP]MOBJECT/EB_BGCOMPILE.o EB.BP]MOBJECT/EBTTCOPY.o EB.BP]MOBJECT/COMPL2.o EB.BP]MOBJECT/jEDIfmt.o EB.BP]MOBJECT/EBKEYTEST.o EB.BP]MOBJECT/$$SVNREVERT

alltargets=bin/EBL bin/EBCRT bin/UNCOMPILED bin/SVNCOMMIT bin/SVNSELECT bin/CONVF2DIR bin/color bin/SVNCHECKOUT bin/SVNDELETE bin/EBKEYS bin/EB_ENABLE bin/lex bin/SVNRENAME bin/D3BASIC bin/COMPARE_ITEM bin/COMPL bin/EB bin/GETSAME bin/EBV bin/EB_BGCOMPILE bin/EBTTCOPY bin/COMPL2 bin/jEDIfmt bin/EBKEYTEST bin/SVNREVERT

targets: $(alltargets) lib/lib.el

all: targets

EB.BP]MOBJECT/EBL.o: EB.BP/EBL.b EB.OS.INCLUDES/GET.TCL.SENTENCE EB.OS.INCLUDES/OS EB.OS.INCLUDES/WHO
	BASIC EB.BP EBL.b

bin/EBL: EB.BP]MOBJECT/EBL.o
	CATALOG -o./bin EB.BP EBL.b

EB.BP]MOBJECT/$$SVN_COMMIT: EB.BP/SVN_COMMIT EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_COMMIT

EB.BP]MOBJECT/$$SVN_SUBVERSION: EB.BP/SVN_SUBVERSION EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_SUBVERSION

EB.BP]MOBJECT/EB_REFINE.o: EB.BP/EB_REFINE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_REFINE.b

EB.BP]MOBJECT/EB_ROTATE.o: EB.BP/EB_ROTATE.b
	BASIC EB.BP EB_ROTATE.b

EB.BP]MOBJECT/$$SVN_CHECKIN: EB.BP/SVN_CHECKIN EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_CHECKIN

EB.BP]MOBJECT/EB_TABCOL.o: EB.BP/EB_TABCOL.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_TABCOL.b

EB.BP]MOBJECT/SPLITFILEPATH.o: EB.BP/SPLITFILEPATH.b
	BASIC EB.BP SPLITFILEPATH.b

EB.BP]MOBJECT/$$SVN_CHECKOUT: EB.BP/SVN_CHECKOUT EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_CHECKOUT

EB.BP]MOBJECT/$$SVN_GET_REPOSITORY: EB.BP/SVN_GET_REPOSITORY EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_GET_REPOSITORY

EB.BP]MOBJECT/EB_SHOWMEMBERS.o: EB.BP/EB_SHOWMEMBERS.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_SHOWMEMBERS.b

EB.BP]MOBJECT/EB_ANCHAR.o: EB.BP/EB_ANCHAR.b
	BASIC EB.BP EB_ANCHAR.b

EB.BP]MOBJECT/EB_UT_BOX.o: EB.BP/EB_UT_BOX.b EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR
	BASIC EB.BP EB_UT_BOX.b

EB.BP]MOBJECT/EBCRT.o: EB.BP/EBCRT.b EB.EQUS/SCREEN.PARAMS
	BASIC EB.BP EBCRT.b

bin/EBCRT: EB.BP]MOBJECT/EBCRT.o
	CATALOG -o./bin EB.BP EBCRT.b

EB.BP]MOBJECT/UNCOMPILED.o: EB.BP/UNCOMPILED.b
	BASIC EB.BP UNCOMPILED.b

bin/UNCOMPILED: EB.BP]MOBJECT/UNCOMPILED.o
	CATALOG -o./bin EB.BP UNCOMPILED.b

EB.BP]MOBJECT/EB_GETRPL.o: EB.BP/EB_GETRPL.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_GETRPL.b

EB.BP]MOBJECT/EB_MOVE.o: EB.BP/EB_MOVE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_MOVE.b

EB.BP]MOBJECT/$$GETFLNM: EB.BP/GETFLNM
	BASIC EB.BP GETFLNM

EB.BP]MOBJECT/lexLine.o: EB.BP/lexLine.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP lexLine.b

EB.BP]MOBJECT/EBGETKEY.o: EB.BP/EBGETKEY.b
	BASIC EB.BP EBGETKEY.b

EB.BP]MOBJECT/EB_BOX.o: EB.BP/EB_BOX.b EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_BOX.b

EB.BP]MOBJECT/$$EB_CH.COLOUR: EB.BP/EB_CH.COLOUR
	BASIC EB.BP EB_CH.COLOUR

EB.BP]MOBJECT/EB_EREPLACE.o: EB.BP/EB_EREPLACE.b
	BASIC EB.BP EB_EREPLACE.b

EB.BP]MOBJECT/initColors.o: EB.BP/initColors.b EB.EQUS/COLOURS EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP initColors.b

EB.BP]MOBJECT/EB_TABS.o: EB.BP/EB_TABS.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_TABS.b

EB.BP]MOBJECT/$$SVN_CASE: EB.BP/SVN_CASE
	BASIC EB.BP SVN_CASE

EB.BP]MOBJECT/$$SVNCOMMIT: EB.BP/SVNCOMMIT EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVNCOMMIT

bin/SVNCOMMIT: EB.BP]MOBJECT/$$SVNCOMMIT
	CATALOG -o./bin EB.BP SVNCOMMIT

EB.BP]MOBJECT/$$SVNSELECT: EB.BP/SVNSELECT EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVNSELECT

bin/SVNSELECT: EB.BP]MOBJECT/$$SVNSELECT
	CATALOG -o./bin EB.BP SVNSELECT

EB.BP]MOBJECT/$$SVN_GETPWD: EB.BP/SVN_GETPWD EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_GETPWD

EB.BP]MOBJECT/EB_VERSION.o: EB.BP/EB_VERSION.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_VERSION.b

EB.BP]MOBJECT/$$SVN_GETROOT: EB.BP/SVN_GETROOT EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_GETROOT

EB.BP]MOBJECT/$$SVN_HISTORY: EB.BP/SVN_HISTORY EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_HISTORY

EB.BP]MOBJECT/EB_FILE.o: EB.BP/EB_FILE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS
	BASIC EB.BP EB_FILE.b

EB.BP]MOBJECT/EB_TCL.o: EB.BP/EB_TCL.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.CRT.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/ED.STACK EB.OS.INCLUDES/ED.STACK.NOCAP EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.TIMEOUT EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS EB.OS.INCLUDES/TCL.EXEC.CMD EB.OS.INCLUDES/TCL.MERGE EB.OS.INCLUDES/TCL.PARAMS EB.OS.INCLUDES/TIMEOUT.OFF
	BASIC EB.BP EB_TCL.b

EB.BP]MOBJECT/SVN_READ.o: EB.BP/SVN_READ.b EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_READ.b

EB.BP]MOBJECT/EB_ADD.o: EB.BP/EB_ADD.b
	BASIC EB.BP EB_ADD.b

EB.BP]MOBJECT/CONVF2DIR.o: EB.BP/CONVF2DIR.b
	BASIC EB.BP CONVF2DIR.b

bin/CONVF2DIR: EB.BP]MOBJECT/CONVF2DIR.o
	CATALOG -o./bin EB.BP CONVF2DIR.b

EB.BP]MOBJECT/color.o: EB.BP/color.b
	BASIC EB.BP color.b

bin/color: EB.BP]MOBJECT/color.o
	CATALOG -o./bin EB.BP color.b

EB.BP]MOBJECT/EB_EXPANDFLNM.o: EB.BP/EB_EXPANDFLNM.b EB.INCLUDES/PWD
	BASIC EB.BP EB_EXPANDFLNM.b

EB.BP]MOBJECT/EB_GETTCC.o: EB.BP/EB_GETTCC.b EB.EQUS/TERM.TYPES
	BASIC EB.BP EB_GETTCC.b

EB.BP]MOBJECT/EB_MERGE.o: EB.BP/EB_MERGE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_MERGE.b

EB.BP]MOBJECT/EB_READHEADERS.o: EB.BP/EB_READHEADERS.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_READHEADERS.b

EB.BP]MOBJECT/$$GET_CATALOG_FILES: EB.BP/GET_CATALOG_FILES
	BASIC EB.BP GET_CATALOG_FILES

EB.BP]MOBJECT/$$SVN_UPDATEHIST: EB.BP/SVN_UPDATEHIST EB.INCLUDES/GET.USER EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_UPDATEHIST

EB.BP]MOBJECT/EB_HELP.o: EB.BP/EB_HELP.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS.REL
	BASIC EB.BP EB_HELP.b

EB.BP]MOBJECT/EB_INP.o: EB.BP/EB_INP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_INP.b

EB.BP]MOBJECT/EB_FINDDEC.o: EB.BP/EB_FINDDEC.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_FINDDEC.b

EB.BP]MOBJECT/EB_REPLACE.o: EB.BP/EB_REPLACE.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_REPLACE.b

EB.BP]MOBJECT/EB_VERS_CTRL.o: EB.BP/EB_VERS_CTRL.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/GET.HOME EB.INCLUDES/PWD EB.INCLUDES/SVN_DEBUG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_VERS_CTRL.b

EB.BP]MOBJECT/EB_CLOSE.o: EB.BP/EB_CLOSE.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_CLOSE.b

EB.BP]MOBJECT/EB_CONVCODE.o: EB.BP/EB_CONVCODE.b EB.EQUS/ACT.CODES
	BASIC EB.BP EB_CONVCODE.b

EB.BP]MOBJECT/EB_SWAP.o: EB.BP/EB_SWAP.b
	BASIC EB.BP EB_SWAP.b

EB.BP]MOBJECT/$$SVNCHECKOUT: EB.BP/SVNCHECKOUT EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVNCHECKOUT

bin/SVNCHECKOUT: EB.BP]MOBJECT/$$SVNCHECKOUT
	CATALOG -o./bin EB.BP SVNCHECKOUT

EB.BP]MOBJECT/EB_GETMOUSE.o: EB.BP/EB_GETMOUSE.b
	BASIC EB.BP EB_GETMOUSE.b

EB.BP]MOBJECT/$$SVN_DELETE: EB.BP/SVN_DELETE EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_DELETE

EB.BP]MOBJECT/EB_PASTE.o: EB.BP/EB_PASTE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_PASTE.b

EB.BP]MOBJECT/$$SVN_CLEAN: EB.BP/SVN_CLEAN EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_CLEAN

EB.BP]MOBJECT/$$SVN_OPENHIST: EB.BP/SVN_OPENHIST
	BASIC EB.BP SVN_OPENHIST

EB.BP]MOBJECT/EB_ERRMSG.o: EB.BP/EB_ERRMSG.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_ERRMSG.b

EB.BP]MOBJECT/$$SVN_SRC_STATUS: EB.BP/SVN_SRC_STATUS EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_SRC_STATUS

EB.BP]MOBJECT/EBJSHOW.o: EB.BP/EBJSHOW.b
	BASIC EB.BP EBJSHOW.b

EB.BP]MOBJECT/$$SVNDELETE: EB.BP/SVNDELETE EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVNDELETE

bin/SVNDELETE: EB.BP]MOBJECT/$$SVNDELETE
	CATALOG -o./bin EB.BP SVNDELETE

EB.BP]MOBJECT/EB_SETUPSWITCH.o: EB.BP/EB_SETUPSWITCH.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_SETUPSWITCH.b

EB.BP]MOBJECT/EB_OPEN.o: EB.BP/EB_OPEN.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_OPEN.b

EB.BP]MOBJECT/EB_UT_INIT.o: EB.BP/EB_UT_INIT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.EQUS/TERM.TYPES EB.EQUS/USER_SETTINGS EB.INCLUDES/INPUT.CODES EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS.ERRORS EB.OS.INCLUDES/SKIP.PASSWORD EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/WHO
	BASIC EB.BP EB_UT_INIT.b

EB.BP]MOBJECT/$$SVN_REVERT: EB.BP/SVN_REVERT EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_REVERT

EB.BP]MOBJECT/EBKEYS.o: EB.BP/EBKEYS.b EB.EQUS/EB.CHARS
	BASIC EB.BP EBKEYS.b

bin/EBKEYS: EB.BP]MOBJECT/EBKEYS.o
	CATALOG -o./bin EB.BP EBKEYS.b

EB.BP]MOBJECT/EB_ENABLE.o: EB.BP/EB_ENABLE.b
	BASIC EB.BP EB_ENABLE.b

bin/EB_ENABLE: EB.BP]MOBJECT/EB_ENABLE.o
	CATALOG -o./bin EB.BP EB_ENABLE.b

EB.BP]MOBJECT/lex.o: EB.BP/lex.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP lex.b

bin/lex: EB.BP]MOBJECT/lex.o
	CATALOG -o./bin EB.BP lex.b

EB.BP]MOBJECT/EB_AUTOSAVE.o: EB.BP/EB_AUTOSAVE.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_AUTOSAVE.b

EB.BP]MOBJECT/EB_CHOICES.o: EB.BP/EB_CHOICES.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/DRV.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/REFRESH.CODES EB.EQUS/SCR.CRT.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/USER.EXITS
	BASIC EB.BP EB_CHOICES.b

EB.BP]MOBJECT/EB_READINCL.o: EB.BP/EB_READINCL.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_READINCL.b

EB.BP]MOBJECT/$$SVN_GETCATLID: EB.BP/SVN_GETCATLID EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_GETCATLID

EB.BP]MOBJECT/isComment.o: EB.BP/isComment.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isComment.b

EB.BP]MOBJECT/stringType.o: EB.BP/stringType.b EB.INCLUDES/lexEquates.h
	BASIC EB.BP stringType.b

EB.BP]MOBJECT/$$SVNRENAME: EB.BP/SVNRENAME
	BASIC EB.BP SVNRENAME

bin/SVNRENAME: EB.BP]MOBJECT/$$SVNRENAME
	CATALOG -o./bin EB.BP SVNRENAME

EB.BP]MOBJECT/D3BASIC.o: EB.BP/D3BASIC.b
	BASIC EB.BP D3BASIC.b

bin/D3BASIC: EB.BP]MOBJECT/D3BASIC.o
	CATALOG -o./bin EB.BP D3BASIC.b

EB.BP]MOBJECT/EB_MAKEHIST.o: EB.BP/EB_MAKEHIST.b
	BASIC EB.BP EB_MAKEHIST.b

EB.BP]MOBJECT/EB_CUT.o: EB.BP/EB_CUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_CUT.b

EB.BP]MOBJECT/EB_REFRESH.o: EB.BP/EB_REFRESH.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_REFRESH.b

EB.BP]MOBJECT/EB_SEARCH.o: EB.BP/EB_SEARCH.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/REMOVE.LINE
	BASIC EB.BP EB_SEARCH.b

EB.BP]MOBJECT/EB_UT_INPUT_ZERO.o: EB.BP/EB_UT_INPUT_ZERO.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/STD.EQUS EB.OS.INCLUDES/CHECK.ACT.SUB EB.OS.INCLUDES/CHECK.SUB.SUB EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.DIFF EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.12 EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_UT_INPUT_ZERO.b

EB.BP]MOBJECT/$$SVN_EXEC: EB.BP/SVN_EXEC EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_EXEC

EB.BP]MOBJECT/COMPARE_ITEM.o: EB.BP/COMPARE_ITEM.b EB.EQUS/EB.COMMONS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/CLEARSELECT EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/FIND.NEXT.DIFF EB.OS.INCLUDES/GET.FLNM EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/WHO
	BASIC EB.BP COMPARE_ITEM.b

bin/COMPARE_ITEM: EB.BP]MOBJECT/COMPARE_ITEM.o
	CATALOG -o./bin EB.BP COMPARE_ITEM.b

EB.BP]MOBJECT/$$SVN_GETHOMEPATH: EB.BP/SVN_GETHOMEPATH EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_GETHOMEPATH

EB.BP]MOBJECT/COMPL.o: EB.BP/COMPL.b
	BASIC EB.BP COMPL.b

bin/COMPL: EB.BP]MOBJECT/COMPL.o
	CATALOG -o./bin EB.BP COMPL.b

EB.BP]MOBJECT/EB.o: EB.BP/EB.b EB.EQUS/ACT.CODES EB.EQUS/COLOUR.CODES EB.EQUS/COLOURS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CHECK.B EB.INCLUDES/CRT.LN EB.INCLUDES/EB.CASE EB.INCLUDES/VERS_CTRL EB.INCLUDES/cReserved.h EB.INCLUDES/jbcReserved.h EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/BACKGROUND.VERB EB.OS.INCLUDES/BASIC.OPTS EB.OS.INCLUDES/BASIC.VERB EB.OS.INCLUDES/CATALOG EB.OS.INCLUDES/CLEARSELECT EB.OS.INCLUDES/DECATALOG EB.OS.INCLUDES/DL4.BASIC EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/EB.INIT EB.OS.INCLUDES/EB.LMARGIN EB.OS.INCLUDES/EB.SQL EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/GET.FLNM EB.OS.INCLUDES/GET.TCL.SENTENCE EB.OS.INCLUDES/LOCKED.BY EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS EB.OS.INCLUDES/OS.ERRORS EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/RTED.BASIC EB.OS.INCLUDES/SET.TIMEOUT EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/TIMEOUT.OFF EB.OS.INCLUDES/TIMEOUT.ON EB.OS.INCLUDES/WHO
	BASIC EB.BP EB.b

bin/EB: EB.BP]MOBJECT/EB.o
	CATALOG -o./bin EB.BP EB.b

EB.BP]MOBJECT/$$GETFULLPATH: EB.BP/GETFULLPATH
	BASIC EB.BP GETFULLPATH

EB.BP]MOBJECT/JBCUserConversions.o: EB.BP/JBCUserConversions.b
	BASIC EB.BP JBCUserConversions.b

EB.BP]MOBJECT/GETSAME.o: EB.BP/GETSAME.b
	BASIC EB.BP GETSAME.b

bin/GETSAME: EB.BP]MOBJECT/GETSAME.o
	CATALOG -o./bin EB.BP GETSAME.b

EB.BP]MOBJECT/$$GETYN: EB.BP/GETYN
	BASIC EB.BP GETYN

EB.BP]MOBJECT/EBV.o: EB.BP/EBV.b
	BASIC EB.BP EBV.b

bin/EBV: EB.BP]MOBJECT/EBV.o
	CATALOG -o./bin EB.BP EBV.b

EB.BP]MOBJECT/EB_GET_INPUT.o: EB.BP/EB_GET_INPUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_GET_INPUT.b

EB.BP]MOBJECT/EB_RSS.o: EB.BP/EB_RSS.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_RSS.b

EB.BP]MOBJECT/$$GET_CATALOG_FILE: EB.BP/GET_CATALOG_FILE
	BASIC EB.BP GET_CATALOG_FILE

EB.BP]MOBJECT/EB_BGCOMPILE.o: EB.BP/EB_BGCOMPILE.b
	BASIC EB.BP EB_BGCOMPILE.b

bin/EB_BGCOMPILE: EB.BP]MOBJECT/EB_BGCOMPILE.o
	CATALOG -o./bin EB.BP EB_BGCOMPILE.b

EB.BP]MOBJECT/EB_PRINT.o: EB.BP/EB_PRINT.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_PRINT.b

EB.BP]MOBJECT/$$SVN_ADD: EB.BP/SVN_ADD EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_ADD

EB.BP]MOBJECT/isSeparator.o: EB.BP/isSeparator.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isSeparator.b

EB.BP]MOBJECT/isString.o: EB.BP/isString.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isString.b

EB.BP]MOBJECT/EBTTCOPY.o: EB.BP/EBTTCOPY.b
	BASIC EB.BP EBTTCOPY.b

bin/EBTTCOPY: EB.BP]MOBJECT/EBTTCOPY.o
	CATALOG -o./bin EB.BP EBTTCOPY.b

EB.BP]MOBJECT/EB_INPUT_ZERO.o: EB.BP/EB_INPUT_ZERO.b EB.EQUS/ACT.CODES EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/CHECK.SUB.SUB EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.TIMEOUT EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_INPUT_ZERO.b

EB.BP]MOBJECT/$$SVN_REMOVEHIST: EB.BP/SVN_REMOVEHIST EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_REMOVEHIST

EB.BP]MOBJECT/nextToken.o: EB.BP/nextToken.b EB.INCLUDES/lexCharTypes.h
	BASIC EB.BP nextToken.b

EB.BP]MOBJECT/EB_TRIM.o: EB.BP/EB_TRIM.b
	BASIC EB.BP EB_TRIM.b

EB.BP]MOBJECT/$$SVN_GETORIGPATH: EB.BP/SVN_GETORIGPATH
	BASIC EB.BP SVN_GETORIGPATH

EB.BP]MOBJECT/ttvt220_TRANS.o: EB.BP/ttvt220_TRANS.b
	BASIC EB.BP ttvt220_TRANS.b

EB.BP]MOBJECT/EB_ASSIGN_OPEN.o: EB.BP/EB_ASSIGN_OPEN.b EB.EQUS/EB.COMMONS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_ASSIGN_OPEN.b

EB.BP]MOBJECT/$$GET.FILE.STAMP: EB.BP/GET.FILE.STAMP
	BASIC EB.BP GET.FILE.STAMP

EB.BP]MOBJECT/$$SVN_READHIST: EB.BP/SVN_READHIST EB.INCLUDES/GET.USER EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_READHIST

EB.BP]MOBJECT/$$SVN_SENTENCE: EB.BP/SVN_SENTENCE EB.INCLUDES/DISPLAY.SYNTAX EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_SENTENCE

EB.BP]MOBJECT/EB_INPUT.o: EB.BP/EB_INPUT.b EB.EQUS/ACT.CODES EB.EQUS/DRV.PARAMS EB.EQUS/EB.CHARS EB.EQUS/OTHER.PARAMS EB.EQUS/REFRESH.CODES EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/EB.STD.EQUS EB.INCLUDES/EB.WP.SUBROUTINES EB.OS.INCLUDES/AT.MINUS.CODES EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/DATE.CONV EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.DIFF EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.LINE.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/PC.RESET.CURSOR EB.OS.INCLUDES/SYSTEM.12 EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/USER.EXITS EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_INPUT.b

EB.BP]MOBJECT/EB_FIND.o: EB.BP/EB_FIND.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_FIND.b

EB.BP]MOBJECT/EB_MERRMSG.o: EB.BP/EB_MERRMSG.b EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.EQUS/WIN.ARGS EB.INCLUDES/MORE.CHARS EB.INCLUDES/REMOVE.TYPEAHEAD EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/SYSTEM.14
	BASIC EB.BP EB_MERRMSG.b

EB.BP]MOBJECT/EB_FORMAT.o: EB.BP/EB_FORMAT.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_FORMAT.b

EB.BP]MOBJECT/EB_OPEN_FILE.o: EB.BP/EB_OPEN_FILE.b EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_OPEN_FILE.b

EB.BP]MOBJECT/EB_REGEX.o: EB.BP/EB_REGEX.b
	BASIC EB.BP EB_REGEX.b

EB.BP]MOBJECT/$$SVN_SYNC: EB.BP/SVN_SYNC EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVN_SYNC

EB.BP]MOBJECT/isNumber.o: EB.BP/isNumber.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isNumber.b

EB.BP]MOBJECT/isReservedWord.o: EB.BP/isReservedWord.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isReservedWord.b

EB.BP]MOBJECT/COMPL2.o: EB.BP/COMPL2.b
	BASIC EB.BP COMPL2.b

bin/COMPL2: EB.BP]MOBJECT/COMPL2.o
	CATALOG -o./bin EB.BP COMPL2.b

EB.BP]MOBJECT/jEDIfmt.o: EB.BP/jEDIfmt.b
	BASIC EB.BP jEDIfmt.b

bin/jEDIfmt: EB.BP]MOBJECT/jEDIfmt.o
	CATALOG -o./bin EB.BP jEDIfmt.b

EB.BP]MOBJECT/EB_COMPARE.o: EB.BP/EB_COMPARE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_COMPARE.b

EB.BP]MOBJECT/EB_GIT.o: EB.BP/EB_GIT.b
	BASIC EB.BP EB_GIT.b

EB.BP]MOBJECT/EBGETHOME.o: EB.BP/EBGETHOME.b
	BASIC EB.BP EBGETHOME.b

EB.BP]MOBJECT/FNKEYTRANS.o: EB.BP/FNKEYTRANS.b
	BASIC EB.BP FNKEYTRANS.b

EB.BP]MOBJECT/$$SVN_OPENLOCKS: EB.BP/SVN_OPENLOCKS
	BASIC EB.BP SVN_OPENLOCKS

EB.BP]MOBJECT/EBKEYTEST.o: EB.BP/EBKEYTEST.b
	BASIC EB.BP EBKEYTEST.b

bin/EBKEYTEST: EB.BP]MOBJECT/EBKEYTEST.o
	CATALOG -o./bin EB.BP EBKEYTEST.b

EB.BP]MOBJECT/$$SVNREVERT: EB.BP/SVNREVERT EB.INCLUDES/GET.HOME EB.INCLUDES/SVN_DEBUG
	BASIC EB.BP SVNREVERT

bin/SVNREVERT: EB.BP]MOBJECT/$$SVNREVERT
	CATALOG -o./bin EB.BP SVNREVERT

EB.BP]MOBJECT/EB_MARKADJ.o: EB.BP/EB_MARKADJ.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON
	BASIC EB.BP EB_MARKADJ.b

EB.BP]MOBJECT/EB_UT_WP.o: EB.BP/EB_UT_WP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/EB.STD.EQUS EB.INCLUDES/EB.WP.SUBROUTINES EB.OS.INCLUDES/AT.MINUS.CODES EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/DATE.CONV EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/NAMED.COMMON EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.LINE.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/PC.RESET.CURSOR EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/USER.EXITS
	BASIC EB.BP EB_UT_WP.b

EB.BP]MOBJECT/isSpacer.o: EB.BP/isSpacer.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isSpacer.b

lib/lib.el: EB.BP]MOBJECT/$$SVN_COMMIT EB.BP]MOBJECT/$$SVN_SUBVERSION EB.BP]MOBJECT/EB_REFINE.o EB.BP]MOBJECT/EB_ROTATE.o EB.BP]MOBJECT/$$SVN_CHECKIN EB.BP]MOBJECT/EB_TABCOL.o EB.BP]MOBJECT/SPLITFILEPATH.o EB.BP]MOBJECT/$$SVN_CHECKOUT EB.BP]MOBJECT/$$SVN_GET_REPOSITORY EB.BP]MOBJECT/EB_SHOWMEMBERS.o EB.BP]MOBJECT/EB_ANCHAR.o EB.BP]MOBJECT/EB_UT_BOX.o EB.BP]MOBJECT/EB_GETRPL.o EB.BP]MOBJECT/EB_MOVE.o EB.BP]MOBJECT/$$GETFLNM EB.BP]MOBJECT/lexLine.o EB.BP]MOBJECT/EBGETKEY.o EB.BP]MOBJECT/EB_BOX.o EB.BP]MOBJECT/$$EB_CH.COLOUR EB.BP]MOBJECT/EB_EREPLACE.o EB.BP]MOBJECT/initColors.o EB.BP]MOBJECT/EB_TABS.o EB.BP]MOBJECT/$$SVN_CASE EB.BP]MOBJECT/$$SVN_GETPWD EB.BP]MOBJECT/EB_VERSION.o EB.BP]MOBJECT/$$SVN_GETROOT EB.BP]MOBJECT/$$SVN_HISTORY EB.BP]MOBJECT/EB_FILE.o EB.BP]MOBJECT/EB_TCL.o EB.BP]MOBJECT/SVN_READ.o EB.BP]MOBJECT/EB_ADD.o EB.BP]MOBJECT/EB_EXPANDFLNM.o EB.BP]MOBJECT/EB_GETTCC.o EB.BP]MOBJECT/EB_MERGE.o EB.BP]MOBJECT/EB_READHEADERS.o EB.BP]MOBJECT/$$GET_CATALOG_FILES EB.BP]MOBJECT/$$SVN_UPDATEHIST EB.BP]MOBJECT/EB_HELP.o EB.BP]MOBJECT/EB_INP.o EB.BP]MOBJECT/EB_FINDDEC.o EB.BP]MOBJECT/EB_REPLACE.o EB.BP]MOBJECT/EB_VERS_CTRL.o EB.BP]MOBJECT/EB_CLOSE.o EB.BP]MOBJECT/EB_CONVCODE.o EB.BP]MOBJECT/EB_SWAP.o EB.BP]MOBJECT/EB_GETMOUSE.o EB.BP]MOBJECT/$$SVN_DELETE EB.BP]MOBJECT/EB_PASTE.o EB.BP]MOBJECT/$$SVN_CLEAN EB.BP]MOBJECT/$$SVN_OPENHIST EB.BP]MOBJECT/EB_ERRMSG.o EB.BP]MOBJECT/$$SVN_SRC_STATUS EB.BP]MOBJECT/EBJSHOW.o EB.BP]MOBJECT/EB_SETUPSWITCH.o EB.BP]MOBJECT/EB_OPEN.o EB.BP]MOBJECT/EB_UT_INIT.o EB.BP]MOBJECT/$$SVN_REVERT EB.BP]MOBJECT/EB_AUTOSAVE.o EB.BP]MOBJECT/EB_CHOICES.o EB.BP]MOBJECT/EB_READINCL.o EB.BP]MOBJECT/$$SVN_GETCATLID EB.BP]MOBJECT/isComment.o EB.BP]MOBJECT/stringType.o EB.BP]MOBJECT/EB_MAKEHIST.o EB.BP]MOBJECT/EB_CUT.o EB.BP]MOBJECT/EB_REFRESH.o EB.BP]MOBJECT/EB_SEARCH.o EB.BP]MOBJECT/EB_UT_INPUT_ZERO.o EB.BP]MOBJECT/$$SVN_EXEC EB.BP]MOBJECT/$$SVN_GETHOMEPATH EB.BP]MOBJECT/$$GETFULLPATH EB.BP]MOBJECT/JBCUserConversions.o EB.BP]MOBJECT/$$GETYN EB.BP]MOBJECT/EB_GET_INPUT.o EB.BP]MOBJECT/EB_RSS.o EB.BP]MOBJECT/$$GET_CATALOG_FILE EB.BP]MOBJECT/EB_PRINT.o EB.BP]MOBJECT/$$SVN_ADD EB.BP]MOBJECT/isSeparator.o EB.BP]MOBJECT/isString.o EB.BP]MOBJECT/EB_INPUT_ZERO.o EB.BP]MOBJECT/$$SVN_REMOVEHIST EB.BP]MOBJECT/nextToken.o EB.BP]MOBJECT/EB_TRIM.o EB.BP]MOBJECT/$$SVN_GETORIGPATH EB.BP]MOBJECT/ttvt220_TRANS.o EB.BP]MOBJECT/EB_ASSIGN_OPEN.o EB.BP]MOBJECT/$$GET.FILE.STAMP EB.BP]MOBJECT/$$SVN_READHIST EB.BP]MOBJECT/$$SVN_SENTENCE EB.BP]MOBJECT/EB_INPUT.o EB.BP]MOBJECT/EB_FIND.o EB.BP]MOBJECT/EB_MERRMSG.o EB.BP]MOBJECT/EB_FORMAT.o EB.BP]MOBJECT/EB_OPEN_FILE.o EB.BP]MOBJECT/EB_REGEX.o EB.BP]MOBJECT/$$SVN_SYNC EB.BP]MOBJECT/isNumber.o EB.BP]MOBJECT/isReservedWord.o EB.BP]MOBJECT/EB_COMPARE.o EB.BP]MOBJECT/EB_GIT.o EB.BP]MOBJECT/EBGETHOME.o EB.BP]MOBJECT/FNKEYTRANS.o EB.BP]MOBJECT/$$SVN_OPENLOCKS EB.BP]MOBJECT/EB_MARKADJ.o EB.BP]MOBJECT/EB_UT_WP.o EB.BP]MOBJECT/isSpacer.o
	CATALOG -L./lib EB.BP $(subst EB.BP]MOBJECT/,,$(patsubst %.o,%.b,$(patsubst $$%,%,$(?))))

clean:
	rm -f $(libobjs)
	rm -f $(binobjs)
