libobjs=EB.BP]MOBJECT/EBGETHOME.o EB.BP]MOBJECT/EBGETKEY.o EB.BP]MOBJECT/EBJSHOW.o EB.BP]MOBJECT/EB_ADD.o EB.BP]MOBJECT/EB_ANCHAR.o EB.BP]MOBJECT/EB_ASSIGN_OPEN.o EB.BP]MOBJECT/EB_AUTOSAVE.o EB.BP]MOBJECT/EB_BOX.o EB.BP]MOBJECT/EB_CHOICES.o EB.BP]MOBJECT/EB_CH_COLOUR.o EB.BP]MOBJECT/EB_CLOSE.o EB.BP]MOBJECT/EB_COMPARE.o EB.BP]MOBJECT/EB_CONVCODE.o EB.BP]MOBJECT/EB_CUT.o EB.BP]MOBJECT/EB_EREPLACE.o EB.BP]MOBJECT/EB_ERRMSG.o EB.BP]MOBJECT/EB_EXPANDFLNM.o EB.BP]MOBJECT/EB_FILE.o EB.BP]MOBJECT/EB_FIND.o EB.BP]MOBJECT/EB_FINDDEC.o EB.BP]MOBJECT/EB_FORMAT.o EB.BP]MOBJECT/EB_GETMOUSE.o EB.BP]MOBJECT/EB_GETRPL.o EB.BP]MOBJECT/EB_GETTCC.o EB.BP]MOBJECT/EB_GET_INPUT.o EB.BP]MOBJECT/EB_HELP.o EB.BP]MOBJECT/EB_INP.o EB.BP]MOBJECT/EB_INPUT.o EB.BP]MOBJECT/EB_INPUT_ZERO.o EB.BP]MOBJECT/EB_INTEGRATE.o EB.BP]MOBJECT/EB_MAKEHIST.o EB.BP]MOBJECT/EB_MARKADJ.o EB.BP]MOBJECT/EB_MERGE.o EB.BP]MOBJECT/EB_MERRMSG.o EB.BP]MOBJECT/EB_MOVE.o EB.BP]MOBJECT/EB_OPEN.o EB.BP]MOBJECT/EB_OPEN_FILE.o EB.BP]MOBJECT/EB_PASTE.o EB.BP]MOBJECT/EB_PRINT.o EB.BP]MOBJECT/EB_READHEADERS.o EB.BP]MOBJECT/EB_READINCL.o EB.BP]MOBJECT/EB_REFINE.o EB.BP]MOBJECT/EB_REFRESH.o EB.BP]MOBJECT/EB_REGEX.o EB.BP]MOBJECT/EB_REPLACE.o EB.BP]MOBJECT/EB_ROTATE.o EB.BP]MOBJECT/EB_RSS.o EB.BP]MOBJECT/EB_SEARCH.o EB.BP]MOBJECT/EB_SETUPSWITCH.o EB.BP]MOBJECT/EB_SHOWMEMBERS.o EB.BP]MOBJECT/EB_SWAP.o EB.BP]MOBJECT/EB_TABCOL.o EB.BP]MOBJECT/EB_TABS.o EB.BP]MOBJECT/EB_TCL.o EB.BP]MOBJECT/EB_TRIM.o EB.BP]MOBJECT/EB_UT_BOX.o EB.BP]MOBJECT/EB_UT_INIT.o EB.BP]MOBJECT/EB_UT_INPUT_ZERO.o EB.BP]MOBJECT/EB_UT_WP.o EB.BP]MOBJECT/EB_VERSION.o EB.BP]MOBJECT/EB_VERS_CTRL.o EB.BP]MOBJECT/FNKEYTRANS.o EB.BP]MOBJECT/GETFLNM.o EB.BP]MOBJECT/GETFULLPATH.o EB.BP]MOBJECT/GETSRCTYPE.o EB.BP]MOBJECT/GETYN.o EB.BP]MOBJECT/GET_CATALOG_FILE.o EB.BP]MOBJECT/GET_CATALOG_FILES.o EB.BP]MOBJECT/GIT_ADD.o EB.BP]MOBJECT/GIT_CHECKIN.o EB.BP]MOBJECT/GIT_CHECKOUT.o EB.BP]MOBJECT/GIT_CLEAN.o EB.BP]MOBJECT/GIT_COMMIT.o EB.BP]MOBJECT/GIT_DELETE.o EB.BP]MOBJECT/GIT_EXEC.o EB.BP]MOBJECT/GIT_GETCATLID.o EB.BP]MOBJECT/GIT_GETHOMEPATH.o EB.BP]MOBJECT/GIT_GETORIGPATH.o EB.BP]MOBJECT/GIT_GETPWD.o EB.BP]MOBJECT/GIT_GETROOT.o EB.BP]MOBJECT/GIT_GET_REPOSITORY.o EB.BP]MOBJECT/GIT_HISTORY.o EB.BP]MOBJECT/GIT_READ.o EB.BP]MOBJECT/GIT_REPOSITORY.o EB.BP]MOBJECT/GIT_REVERT.o EB.BP]MOBJECT/GIT_SRC_STATUS.o EB.BP]MOBJECT/GIT_SYNC.o EB.BP]MOBJECT/JBCUserConversions.o EB.BP]MOBJECT/SPLITFILEPATH.o EB.BP]MOBJECT/SRCPUSH.o EB.BP]MOBJECT/SRC_ADD.o EB.BP]MOBJECT/SRC_CASE.o EB.BP]MOBJECT/SRC_CHECKIN.o EB.BP]MOBJECT/SRC_CHECKOUT.o EB.BP]MOBJECT/SRC_CLEAN.o EB.BP]MOBJECT/SRC_COMMIT.o EB.BP]MOBJECT/SRC_DELETE.o EB.BP]MOBJECT/SRC_EXEC.o EB.BP]MOBJECT/SRC_GETCATLID.o EB.BP]MOBJECT/SRC_GETHOMEPATH.o EB.BP]MOBJECT/SRC_GETORIGPATH.o EB.BP]MOBJECT/SRC_GETPWD.o EB.BP]MOBJECT/SRC_GETROOT.o EB.BP]MOBJECT/SRC_GET_REPOSITORY.o EB.BP]MOBJECT/SRC_HISTORY.o EB.BP]MOBJECT/SRC_OPENHIST.o EB.BP]MOBJECT/SRC_OPENLOCKS.o EB.BP]MOBJECT/SRC_READ.o EB.BP]MOBJECT/SRC_READHIST.o EB.BP]MOBJECT/SRC_REMOVEHIST.o EB.BP]MOBJECT/SRC_REPOSITORY.o EB.BP]MOBJECT/SRC_REVERT.o EB.BP]MOBJECT/SRC_SENTENCE.o EB.BP]MOBJECT/SRC_SRC_STATUS.o EB.BP]MOBJECT/SRC_SYNC.o EB.BP]MOBJECT/SRC_UPDATEHIST.o EB.BP]MOBJECT/SVN_ADD.o EB.BP]MOBJECT/SVN_CHECKIN.o EB.BP]MOBJECT/SVN_CHECKOUT.o EB.BP]MOBJECT/SVN_CLEAN.o EB.BP]MOBJECT/SVN_COMMIT.o EB.BP]MOBJECT/SVN_DELETE.o EB.BP]MOBJECT/SVN_EXEC.o EB.BP]MOBJECT/SVN_GETCATLID.o EB.BP]MOBJECT/SVN_GETHOMEPATH.o EB.BP]MOBJECT/SVN_GETORIGPATH.o EB.BP]MOBJECT/SVN_GETPWD.o EB.BP]MOBJECT/SVN_GETROOT.o EB.BP]MOBJECT/SVN_GET_REPOSITORY.o EB.BP]MOBJECT/SVN_HISTORY.o EB.BP]MOBJECT/SVN_READ.o EB.BP]MOBJECT/SVN_REPOSITORY.o EB.BP]MOBJECT/SVN_REVERT.o EB.BP]MOBJECT/SVN_SRC_STATUS.o EB.BP]MOBJECT/SVN_SYNC.o EB.BP]MOBJECT/initColors.o EB.BP]MOBJECT/isComment.o EB.BP]MOBJECT/isNumber.o EB.BP]MOBJECT/isReservedWord.o EB.BP]MOBJECT/isSeparator.o EB.BP]MOBJECT/isSpacer.o EB.BP]MOBJECT/isString.o EB.BP]MOBJECT/lexLine.o EB.BP]MOBJECT/nextToken.o EB.BP]MOBJECT/stringType.o EB.BP]MOBJECT/ttvt220_TRANS.o
binobjs=EB.BP]MOBJECT/COMPARE_ITEM.o EB.BP]MOBJECT/COMPL.o EB.BP]MOBJECT/COMPL2.o EB.BP]MOBJECT/CONVF2DIR.o EB.BP]MOBJECT/D3BASIC.o EB.BP]MOBJECT/EB.o EB.BP]MOBJECT/EBCRT.o EB.BP]MOBJECT/EBFIND.o EB.BP]MOBJECT/EBKEYS.o EB.BP]MOBJECT/EBKEYTEST.o EB.BP]MOBJECT/EBL.o EB.BP]MOBJECT/EBTTCOPY.o EB.BP]MOBJECT/EBV.o EB.BP]MOBJECT/EB_BGCOMPILE.o EB.BP]MOBJECT/EB_ENABLE.o EB.BP]MOBJECT/GETSAME.o EB.BP]MOBJECT/GITCHECKOUT.o EB.BP]MOBJECT/GITCOMMIT.o EB.BP]MOBJECT/GITDELETE.o EB.BP]MOBJECT/GITRENAME.o EB.BP]MOBJECT/GITREVERT.o EB.BP]MOBJECT/GITSELECT.o EB.BP]MOBJECT/SRCCHECKOUT.o EB.BP]MOBJECT/SRCCOMMIT.o EB.BP]MOBJECT/SRCDELETE.o EB.BP]MOBJECT/SRCRENAME.o EB.BP]MOBJECT/SRCREVERT.o EB.BP]MOBJECT/SRCSELECT.o EB.BP]MOBJECT/SVNCHECKOUT.o EB.BP]MOBJECT/SVNCOMMIT.o EB.BP]MOBJECT/SVNDELETE.o EB.BP]MOBJECT/SVNRENAME.o EB.BP]MOBJECT/SVNREVERT.o EB.BP]MOBJECT/SVNSELECT.o EB.BP]MOBJECT/UNCOMPILED.o EB.BP]MOBJECT/color.o EB.BP]MOBJECT/jEDIfmt.o EB.BP]MOBJECT/lex.o

alltargets=bin/COMPARE_ITEM bin/COMPL bin/COMPL2 bin/CONVF2DIR bin/D3BASIC bin/EB bin/EBCRT bin/EBFIND bin/EBKEYS bin/EBKEYTEST bin/EBL bin/EBTTCOPY bin/EBV bin/EB_BGCOMPILE bin/EB_ENABLE bin/GETSAME bin/GITCHECKOUT bin/GITCOMMIT bin/GITDELETE bin/GITRENAME bin/GITREVERT bin/GITSELECT bin/SRCCHECKOUT bin/SRCCOMMIT bin/SRCDELETE bin/SRCRENAME bin/SRCREVERT bin/SRCSELECT bin/SVNCHECKOUT bin/SVNCOMMIT bin/SVNDELETE bin/SVNRENAME bin/SVNREVERT bin/SVNSELECT bin/UNCOMPILED bin/color bin/jEDIfmt bin/lex

targets: $(alltargets) lib/lib.el
define catlib
echo "" $(foreach fname,$(?),&& CATALOG -L./lib $(firstword $(subst /, ,$(fname))) $(word 2,$(subst /, ,$(fname))))
endef

all: targets

EB.BP]MOBJECT/COMPARE_ITEM.o: EB.BP/COMPARE_ITEM.b EB.EQUS/EB.COMMONS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/CLEARSELECT EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/FIND.NEXT.DIFF EB.OS.INCLUDES/GET.FLNM EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/WHO
	BASIC EB.BP COMPARE_ITEM.b

bin/COMPARE_ITEM: EB.BP]MOBJECT/COMPARE_ITEM.o
	CATALOG -o./bin EB.BP COMPARE_ITEM.b

EB.BP]MOBJECT/COMPL.o: EB.BP/COMPL.b
	BASIC EB.BP COMPL.b

bin/COMPL: EB.BP]MOBJECT/COMPL.o
	CATALOG -o./bin EB.BP COMPL.b

EB.BP]MOBJECT/COMPL2.o: EB.BP/COMPL2.b
	BASIC EB.BP COMPL2.b

bin/COMPL2: EB.BP]MOBJECT/COMPL2.o
	CATALOG -o./bin EB.BP COMPL2.b

EB.BP]MOBJECT/CONVF2DIR.o: EB.BP/CONVF2DIR.b
	BASIC EB.BP CONVF2DIR.b

bin/CONVF2DIR: EB.BP]MOBJECT/CONVF2DIR.o
	CATALOG -o./bin EB.BP CONVF2DIR.b

EB.BP]MOBJECT/D3BASIC.o: EB.BP/D3BASIC.b
	BASIC EB.BP D3BASIC.b

bin/D3BASIC: EB.BP]MOBJECT/D3BASIC.o
	CATALOG -o./bin EB.BP D3BASIC.b

EB.BP]MOBJECT/EB.o: EB.BP/EB.b EB.EQUS/ACT.CODES EB.EQUS/COLOUR.CODES EB.EQUS/COLOURS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CHECK.B EB.INCLUDES/CRT.LN EB.INCLUDES/EB.CASE EB.INCLUDES/VERS_CTRL EB.INCLUDES/cReserved.h EB.INCLUDES/jbcReserved.h EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/BACKGROUND.VERB EB.OS.INCLUDES/BASIC.OPTS EB.OS.INCLUDES/BASIC.VERB EB.OS.INCLUDES/CATALOG EB.OS.INCLUDES/CLEARSELECT EB.OS.INCLUDES/DECATALOG EB.OS.INCLUDES/DL4.BASIC EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/EB.INIT EB.OS.INCLUDES/EB.LMARGIN EB.OS.INCLUDES/EB.SQL EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/GET.FLNM EB.OS.INCLUDES/GET.TCL.SENTENCE EB.OS.INCLUDES/LOCKED.BY EB.OS.INCLUDES/OS EB.OS.INCLUDES/OS.ERRORS EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/RTED.BASIC EB.OS.INCLUDES/SET.TIMEOUT EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/TIMEOUT.OFF EB.OS.INCLUDES/TIMEOUT.ON EB.OS.INCLUDES/WHO
	BASIC EB.BP EB.b

bin/EB: EB.BP]MOBJECT/EB.o
	CATALOG -o./bin EB.BP EB.b
	cp ./bin/EB ./bin/eb
	cp ./bin/EB.so ./bin/eb.so
	cp ./bin/EB.so.el ./bin/eb.so.el

EB.BP]MOBJECT/EBCRT.o: EB.BP/EBCRT.b EB.EQUS/SCREEN.PARAMS
	BASIC EB.BP EBCRT.b

bin/EBCRT: EB.BP]MOBJECT/EBCRT.o
	CATALOG -o./bin EB.BP EBCRT.b

EB.BP]MOBJECT/EBFIND.o: EB.BP/EBFIND.b
	BASIC EB.BP EBFIND.b

bin/EBFIND: EB.BP]MOBJECT/EBFIND.o
	CATALOG -o./bin EB.BP EBFIND.b

EB.BP]MOBJECT/EBGETHOME.o: EB.BP/EBGETHOME.b
	BASIC EB.BP EBGETHOME.b

EB.BP]MOBJECT/EBGETKEY.o: EB.BP/EBGETKEY.b
	BASIC EB.BP EBGETKEY.b

EB.BP]MOBJECT/EBJSHOW.o: EB.BP/EBJSHOW.b
	BASIC EB.BP EBJSHOW.b

EB.BP]MOBJECT/EBKEYS.o: EB.BP/EBKEYS.b EB.EQUS/EB.CHARS
	BASIC EB.BP EBKEYS.b

bin/EBKEYS: EB.BP]MOBJECT/EBKEYS.o
	CATALOG -o./bin EB.BP EBKEYS.b

EB.BP]MOBJECT/EBKEYTEST.o: EB.BP/EBKEYTEST.b
	BASIC EB.BP EBKEYTEST.b

bin/EBKEYTEST: EB.BP]MOBJECT/EBKEYTEST.o
	CATALOG -o./bin EB.BP EBKEYTEST.b

EB.BP]MOBJECT/EBL.o: EB.BP/EBL.b EB.OS.INCLUDES/GET.TCL.SENTENCE EB.OS.INCLUDES/OS EB.OS.INCLUDES/WHO
	BASIC EB.BP EBL.b

bin/EBL: EB.BP]MOBJECT/EBL.o
	CATALOG -o./bin EB.BP EBL.b

EB.BP]MOBJECT/EBTTCOPY.o: EB.BP/EBTTCOPY.b
	BASIC EB.BP EBTTCOPY.b

bin/EBTTCOPY: EB.BP]MOBJECT/EBTTCOPY.o
	CATALOG -o./bin EB.BP EBTTCOPY.b

EB.BP]MOBJECT/EBV.o: EB.BP/EBV.b
	BASIC EB.BP EBV.b

bin/EBV: EB.BP]MOBJECT/EBV.o
	CATALOG -o./bin EB.BP EBV.b

EB.BP]MOBJECT/EB_ADD.o: EB.BP/EB_ADD.b
	BASIC EB.BP EB_ADD.b

EB.BP]MOBJECT/EB_ANCHAR.o: EB.BP/EB_ANCHAR.b
	BASIC EB.BP EB_ANCHAR.b

EB.BP]MOBJECT/EB_ASSIGN_OPEN.o: EB.BP/EB_ASSIGN_OPEN.b EB.EQUS/EB.COMMONS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_ASSIGN_OPEN.b

EB.BP]MOBJECT/EB_AUTOSAVE.o: EB.BP/EB_AUTOSAVE.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_AUTOSAVE.b

EB.BP]MOBJECT/EB_BGCOMPILE.o: EB.BP/EB_BGCOMPILE.b
	BASIC EB.BP EB_BGCOMPILE.b

bin/EB_BGCOMPILE: EB.BP]MOBJECT/EB_BGCOMPILE.o
	CATALOG -o./bin EB.BP EB_BGCOMPILE.b

EB.BP]MOBJECT/EB_BOX.o: EB.BP/EB_BOX.b EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_BOX.b

EB.BP]MOBJECT/EB_CHOICES.o: EB.BP/EB_CHOICES.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/DRV.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/REFRESH.CODES EB.EQUS/SCR.CRT.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/USER.EXITS
	BASIC EB.BP EB_CHOICES.b

EB.BP]MOBJECT/EB_CH_COLOUR.o: EB.BP/EB_CH_COLOUR.b
	BASIC EB.BP EB_CH_COLOUR.b

EB.BP]MOBJECT/EB_CLOSE.o: EB.BP/EB_CLOSE.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_CLOSE.b

EB.BP]MOBJECT/EB_COMPARE.o: EB.BP/EB_COMPARE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_COMPARE.b

EB.BP]MOBJECT/EB_CONVCODE.o: EB.BP/EB_CONVCODE.b EB.EQUS/ACT.CODES
	BASIC EB.BP EB_CONVCODE.b

EB.BP]MOBJECT/EB_CUT.o: EB.BP/EB_CUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_CUT.b

EB.BP]MOBJECT/EB_ENABLE.o: EB.BP/EB_ENABLE.b
	BASIC EB.BP EB_ENABLE.b

bin/EB_ENABLE: EB.BP]MOBJECT/EB_ENABLE.o
	CATALOG -o./bin EB.BP EB_ENABLE.b

EB.BP]MOBJECT/EB_EREPLACE.o: EB.BP/EB_EREPLACE.b
	BASIC EB.BP EB_EREPLACE.b

EB.BP]MOBJECT/EB_ERRMSG.o: EB.BP/EB_ERRMSG.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_ERRMSG.b

EB.BP]MOBJECT/EB_EXPANDFLNM.o: EB.BP/EB_EXPANDFLNM.b EB.INCLUDES/PWD
	BASIC EB.BP EB_EXPANDFLNM.b

EB.BP]MOBJECT/EB_FILE.o: EB.BP/EB_FILE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS
	BASIC EB.BP EB_FILE.b

EB.BP]MOBJECT/EB_FIND.o: EB.BP/EB_FIND.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_FIND.b

EB.BP]MOBJECT/EB_FINDDEC.o: EB.BP/EB_FINDDEC.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_FINDDEC.b

EB.BP]MOBJECT/EB_FORMAT.o: EB.BP/EB_FORMAT.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_FORMAT.b

EB.BP]MOBJECT/EB_GETMOUSE.o: EB.BP/EB_GETMOUSE.b
	BASIC EB.BP EB_GETMOUSE.b

EB.BP]MOBJECT/EB_GETRPL.o: EB.BP/EB_GETRPL.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_GETRPL.b

EB.BP]MOBJECT/EB_GETTCC.o: EB.BP/EB_GETTCC.b EB.EQUS/TERM.TYPES
	BASIC EB.BP EB_GETTCC.b

EB.BP]MOBJECT/EB_GET_INPUT.o: EB.BP/EB_GET_INPUT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_GET_INPUT.b

EB.BP]MOBJECT/EB_HELP.o: EB.BP/EB_HELP.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.REL
	BASIC EB.BP EB_HELP.b

EB.BP]MOBJECT/EB_INP.o: EB.BP/EB_INP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_INP.b

EB.BP]MOBJECT/EB_INPUT.o: EB.BP/EB_INPUT.b EB.EQUS/ACT.CODES EB.EQUS/DRV.PARAMS EB.EQUS/EB.CHARS EB.EQUS/OTHER.PARAMS EB.EQUS/REFRESH.CODES EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/EB.STD.EQUS EB.INCLUDES/EB.WP.SUBROUTINES EB.OS.INCLUDES/AT.MINUS.CODES EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/DATE.CONV EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.DIFF EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.LINE.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/PC.RESET.CURSOR EB.OS.INCLUDES/SYSTEM.12 EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/USER.EXITS EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_INPUT.b

EB.BP]MOBJECT/EB_INPUT_ZERO.o: EB.BP/EB_INPUT_ZERO.b EB.EQUS/ACT.CODES EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/CHECK.SUB.SUB EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.TIMEOUT EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_INPUT_ZERO.b

EB.BP]MOBJECT/EB_INTEGRATE.o: EB.BP/EB_INTEGRATE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_INTEGRATE.b

EB.BP]MOBJECT/EB_MAKEHIST.o: EB.BP/EB_MAKEHIST.b
	BASIC EB.BP EB_MAKEHIST.b

EB.BP]MOBJECT/EB_MARKADJ.o: EB.BP/EB_MARKADJ.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_MARKADJ.b

EB.BP]MOBJECT/EB_MERGE.o: EB.BP/EB_MERGE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_MERGE.b

EB.BP]MOBJECT/EB_MERRMSG.o: EB.BP/EB_MERRMSG.b EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.EQUS/WIN.ARGS EB.INCLUDES/MORE.CHARS EB.INCLUDES/REMOVE.TYPEAHEAD EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.14
	BASIC EB.BP EB_MERRMSG.b

EB.BP]MOBJECT/EB_MOVE.o: EB.BP/EB_MOVE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_MOVE.b

EB.BP]MOBJECT/EB_OPEN.o: EB.BP/EB_OPEN.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS
	BASIC EB.BP EB_OPEN.b

EB.BP]MOBJECT/EB_OPEN_FILE.o: EB.BP/EB_OPEN_FILE.b EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_OPEN_FILE.b

EB.BP]MOBJECT/EB_PASTE.o: EB.BP/EB_PASTE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_PASTE.b

EB.BP]MOBJECT/EB_PRINT.o: EB.BP/EB_PRINT.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_PRINT.b

EB.BP]MOBJECT/EB_READHEADERS.o: EB.BP/EB_READHEADERS.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_READHEADERS.b

EB.BP]MOBJECT/EB_READINCL.o: EB.BP/EB_READINCL.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_READINCL.b

EB.BP]MOBJECT/EB_REFINE.o: EB.BP/EB_REFINE.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_REFINE.b

EB.BP]MOBJECT/EB_REFRESH.o: EB.BP/EB_REFRESH.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_REFRESH.b

EB.BP]MOBJECT/EB_REGEX.o: EB.BP/EB_REGEX.b
	BASIC EB.BP EB_REGEX.b

EB.BP]MOBJECT/EB_REPLACE.o: EB.BP/EB_REPLACE.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_REPLACE.b

EB.BP]MOBJECT/EB_ROTATE.o: EB.BP/EB_ROTATE.b
	BASIC EB.BP EB_ROTATE.b

EB.BP]MOBJECT/EB_RSS.o: EB.BP/EB_RSS.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_RSS.b

EB.BP]MOBJECT/EB_SEARCH.o: EB.BP/EB_SEARCH.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/REMOVE.LINE
	BASIC EB.BP EB_SEARCH.b

EB.BP]MOBJECT/EB_SETUPSWITCH.o: EB.BP/EB_SETUPSWITCH.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_SETUPSWITCH.b

EB.BP]MOBJECT/EB_SHOWMEMBERS.o: EB.BP/EB_SHOWMEMBERS.b EB.EQUS/ACT.CODES EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/CRT.LN EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_SHOWMEMBERS.b

EB.BP]MOBJECT/EB_SWAP.o: EB.BP/EB_SWAP.b
	BASIC EB.BP EB_SWAP.b

EB.BP]MOBJECT/EB_TABCOL.o: EB.BP/EB_TABCOL.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_TABCOL.b

EB.BP]MOBJECT/EB_TABS.o: EB.BP/EB_TABS.b EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_TABS.b

EB.BP]MOBJECT/EB_TCL.o: EB.BP/EB_TCL.b EB.EQUS/ACT.CODES EB.EQUS/COLOURS EB.EQUS/CRT.PARAMS EB.EQUS/EB.CHARS EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCR.CRT.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/ED.STACK EB.OS.INCLUDES/ED.STACK.NOCAP EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/INPUT.TIMEOUT EB.OS.INCLUDES/OS EB.OS.INCLUDES/TCL.EXEC.CMD EB.OS.INCLUDES/TCL.MERGE EB.OS.INCLUDES/TCL.PARAMS EB.OS.INCLUDES/TIMEOUT.OFF
	BASIC EB.BP EB_TCL.b

EB.BP]MOBJECT/EB_TRIM.o: EB.BP/EB_TRIM.b
	BASIC EB.BP EB_TRIM.b

EB.BP]MOBJECT/EB_UT_BOX.o: EB.BP/EB_UT_BOX.b EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR
	BASIC EB.BP EB_UT_BOX.b

EB.BP]MOBJECT/EB_UT_INIT.o: EB.BP/EB_UT_INIT.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.EQUS/TERM.TYPES EB.EQUS/USER_SETTINGS EB.INCLUDES/INPUT.CODES EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/OS.ERRORS EB.OS.INCLUDES/SKIP.PASSWORD EB.OS.INCLUDES/TERM.SETTINGS EB.OS.INCLUDES/WHO
	BASIC EB.BP EB_UT_INIT.b

EB.BP]MOBJECT/EB_UT_INPUT_ZERO.o: EB.BP/EB_UT_INPUT_ZERO.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/STD.EQUS EB.OS.INCLUDES/CHECK.ACT.SUB EB.OS.INCLUDES/CHECK.SUB.SUB EB.OS.INCLUDES/INPUT.DELAY EB.OS.INCLUDES/INPUT.DIFF EB.OS.INCLUDES/INPUT.ZERO EB.OS.INCLUDES/SYSTEM.12 EB.OS.INCLUDES/SYSTEM.14 EB.OS.INCLUDES/UT.INPUT.TIMEOUT
	BASIC EB.BP EB_UT_INPUT_ZERO.b

EB.BP]MOBJECT/EB_UT_WP.o: EB.BP/EB_UT_WP.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/EB.STD.EQUS EB.INCLUDES/EB.WP.SUBROUTINES EB.OS.INCLUDES/AT.MINUS.CODES EB.OS.INCLUDES/CHECK.FOR.CMD EB.OS.INCLUDES/DATE.CONV EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON EB.OS.INCLUDES/PC.BLOCK.CURSOR EB.OS.INCLUDES/PC.LINE.CURSOR EB.OS.INCLUDES/PC.OFF.CURSOR EB.OS.INCLUDES/PC.ON.CURSOR EB.OS.INCLUDES/PC.RESET.CURSOR EB.OS.INCLUDES/TODAYS.DATE EB.OS.INCLUDES/USER.EXITS
	BASIC EB.BP EB_UT_WP.b

EB.BP]MOBJECT/EB_VERSION.o: EB.BP/EB_VERSION.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_VERSION.b

EB.BP]MOBJECT/EB_VERS_CTRL.o: EB.BP/EB_VERS_CTRL.b EB.EQUS/ACT.CODES EB.EQUS/EB.CHARS EB.EQUS/EB.COMMON EB.EQUS/EB.COMMONS EB.EQUS/EB.EQUS EB.EQUS/OTHER.PARAMS EB.EQUS/SCREEN.PARAMS EB.EQUS/STD.EQUS EB.INCLUDES/GET.HOME EB.INCLUDES/PWD EB.INCLUDES/SRC_DEBUG EB.OS.INCLUDES/EB.COMMONS EB.OS.INCLUDES/FILE.COMMON
	BASIC EB.BP EB_VERS_CTRL.b

EB.BP]MOBJECT/FNKEYTRANS.o: EB.BP/FNKEYTRANS.b
	BASIC EB.BP FNKEYTRANS.b

EB.BP]MOBJECT/GETFLNM.o: EB.BP/GETFLNM.b
	BASIC EB.BP GETFLNM.b

EB.BP]MOBJECT/GETFULLPATH.o: EB.BP/GETFULLPATH.b
	BASIC EB.BP GETFULLPATH.b

EB.BP]MOBJECT/GETSAME.o: EB.BP/GETSAME.b
	BASIC EB.BP GETSAME.b

bin/GETSAME: EB.BP]MOBJECT/GETSAME.o
	CATALOG -o./bin EB.BP GETSAME.b

EB.BP]MOBJECT/GETSRCTYPE.o: EB.BP/GETSRCTYPE.b
	BASIC EB.BP GETSRCTYPE.b

EB.BP]MOBJECT/GETYN.o: EB.BP/GETYN.b
	BASIC EB.BP GETYN.b

EB.BP]MOBJECT/GET_CATALOG_FILE.o: EB.BP/GET_CATALOG_FILE.b
	BASIC EB.BP GET_CATALOG_FILE.b

EB.BP]MOBJECT/GET_CATALOG_FILES.o: EB.BP/GET_CATALOG_FILES.b
	BASIC EB.BP GET_CATALOG_FILES.b

EB.BP]MOBJECT/GITCHECKOUT.o: EB.BP/GITCHECKOUT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GITCHECKOUT.b

bin/GITCHECKOUT: EB.BP]MOBJECT/GITCHECKOUT.o
	CATALOG -o./bin EB.BP GITCHECKOUT.b

EB.BP]MOBJECT/GITCOMMIT.o: EB.BP/GITCOMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GITCOMMIT.b

bin/GITCOMMIT: EB.BP]MOBJECT/GITCOMMIT.o
	CATALOG -o./bin EB.BP GITCOMMIT.b

EB.BP]MOBJECT/GITDELETE.o: EB.BP/GITDELETE.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GITDELETE.b

bin/GITDELETE: EB.BP]MOBJECT/GITDELETE.o
	CATALOG -o./bin EB.BP GITDELETE.b

EB.BP]MOBJECT/GITRENAME.o: EB.BP/GITRENAME.b
	BASIC EB.BP GITRENAME.b

bin/GITRENAME: EB.BP]MOBJECT/GITRENAME.o
	CATALOG -o./bin EB.BP GITRENAME.b

EB.BP]MOBJECT/GITREVERT.o: EB.BP/GITREVERT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GITREVERT.b

bin/GITREVERT: EB.BP]MOBJECT/GITREVERT.o
	CATALOG -o./bin EB.BP GITREVERT.b

EB.BP]MOBJECT/GITSELECT.o: EB.BP/GITSELECT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GITSELECT.b

bin/GITSELECT: EB.BP]MOBJECT/GITSELECT.o
	CATALOG -o./bin EB.BP GITSELECT.b

EB.BP]MOBJECT/GIT_ADD.o: EB.BP/GIT_ADD.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_ADD.b

EB.BP]MOBJECT/GIT_CHECKIN.o: EB.BP/GIT_CHECKIN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_CHECKIN.b

EB.BP]MOBJECT/GIT_CHECKOUT.o: EB.BP/GIT_CHECKOUT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_CHECKOUT.b

EB.BP]MOBJECT/GIT_CLEAN.o: EB.BP/GIT_CLEAN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_CLEAN.b

EB.BP]MOBJECT/GIT_COMMIT.o: EB.BP/GIT_COMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_COMMIT.b

EB.BP]MOBJECT/GIT_DELETE.o: EB.BP/GIT_DELETE.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_DELETE.b

EB.BP]MOBJECT/GIT_EXEC.o: EB.BP/GIT_EXEC.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_EXEC.b

EB.BP]MOBJECT/GIT_GETCATLID.o: EB.BP/GIT_GETCATLID.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_GETCATLID.b

EB.BP]MOBJECT/GIT_GETHOMEPATH.o: EB.BP/GIT_GETHOMEPATH.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_GETHOMEPATH.b

EB.BP]MOBJECT/GIT_GETORIGPATH.o: EB.BP/GIT_GETORIGPATH.b
	BASIC EB.BP GIT_GETORIGPATH.b

EB.BP]MOBJECT/GIT_GETPWD.o: EB.BP/GIT_GETPWD.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_GETPWD.b

EB.BP]MOBJECT/GIT_GETROOT.o: EB.BP/GIT_GETROOT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_GETROOT.b

EB.BP]MOBJECT/GIT_GET_REPOSITORY.o: EB.BP/GIT_GET_REPOSITORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_GET_REPOSITORY.b

EB.BP]MOBJECT/GIT_HISTORY.o: EB.BP/GIT_HISTORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_HISTORY.b

EB.BP]MOBJECT/GIT_READ.o: EB.BP/GIT_READ.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_READ.b

EB.BP]MOBJECT/GIT_REPOSITORY.o: EB.BP/GIT_REPOSITORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_REPOSITORY.b

EB.BP]MOBJECT/GIT_REVERT.o: EB.BP/GIT_REVERT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_REVERT.b

EB.BP]MOBJECT/GIT_SRC_STATUS.o: EB.BP/GIT_SRC_STATUS.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP GIT_SRC_STATUS.b

EB.BP]MOBJECT/GIT_SYNC.o: EB.BP/GIT_SYNC.b
	BASIC EB.BP GIT_SYNC.b

EB.BP]MOBJECT/JBCUserConversions.o: EB.BP/JBCUserConversions.b
	BASIC EB.BP JBCUserConversions.b

EB.BP]MOBJECT/SPLITFILEPATH.o: EB.BP/SPLITFILEPATH.b
	BASIC EB.BP SPLITFILEPATH.b

EB.BP]MOBJECT/SRCCHECKOUT.o: EB.BP/SRCCHECKOUT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRCCHECKOUT.b

bin/SRCCHECKOUT: EB.BP]MOBJECT/SRCCHECKOUT.o
	CATALOG -o./bin EB.BP SRCCHECKOUT.b

EB.BP]MOBJECT/SRCCOMMIT.o: EB.BP/SRCCOMMIT.b
	BASIC EB.BP SRCCOMMIT.b

bin/SRCCOMMIT: EB.BP]MOBJECT/SRCCOMMIT.o
	CATALOG -o./bin EB.BP SRCCOMMIT.b

EB.BP]MOBJECT/SRCDELETE.o: EB.BP/SRCDELETE.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRCDELETE.b

bin/SRCDELETE: EB.BP]MOBJECT/SRCDELETE.o
	CATALOG -o./bin EB.BP SRCDELETE.b

EB.BP]MOBJECT/SRCPUSH.o: EB.BP/SRCPUSH.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRCPUSH.b

EB.BP]MOBJECT/SRCRENAME.o: EB.BP/SRCRENAME.b
	BASIC EB.BP SRCRENAME.b

bin/SRCRENAME: EB.BP]MOBJECT/SRCRENAME.o
	CATALOG -o./bin EB.BP SRCRENAME.b

EB.BP]MOBJECT/SRCREVERT.o: EB.BP/SRCREVERT.b
	BASIC EB.BP SRCREVERT.b

bin/SRCREVERT: EB.BP]MOBJECT/SRCREVERT.o
	CATALOG -o./bin EB.BP SRCREVERT.b

EB.BP]MOBJECT/SRCSELECT.o: EB.BP/SRCSELECT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRCSELECT.b

bin/SRCSELECT: EB.BP]MOBJECT/SRCSELECT.o
	CATALOG -o./bin EB.BP SRCSELECT.b

EB.BP]MOBJECT/SRC_ADD.o: EB.BP/SRC_ADD.b
	BASIC EB.BP SRC_ADD.b

EB.BP]MOBJECT/SRC_CASE.o: EB.BP/SRC_CASE.b
	BASIC EB.BP SRC_CASE.b

EB.BP]MOBJECT/SRC_CHECKIN.o: EB.BP/SRC_CHECKIN.b
	BASIC EB.BP SRC_CHECKIN.b

EB.BP]MOBJECT/SRC_CHECKOUT.o: EB.BP/SRC_CHECKOUT.b
	BASIC EB.BP SRC_CHECKOUT.b

EB.BP]MOBJECT/SRC_CLEAN.o: EB.BP/SRC_CLEAN.b
	BASIC EB.BP SRC_CLEAN.b

EB.BP]MOBJECT/SRC_COMMIT.o: EB.BP/SRC_COMMIT.b
	BASIC EB.BP SRC_COMMIT.b

EB.BP]MOBJECT/SRC_DELETE.o: EB.BP/SRC_DELETE.b
	BASIC EB.BP SRC_DELETE.b

EB.BP]MOBJECT/SRC_EXEC.o: EB.BP/SRC_EXEC.b
	BASIC EB.BP SRC_EXEC.b

EB.BP]MOBJECT/SRC_GETCATLID.o: EB.BP/SRC_GETCATLID.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_GETCATLID.b

EB.BP]MOBJECT/SRC_GETHOMEPATH.o: EB.BP/SRC_GETHOMEPATH.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_GETHOMEPATH.b

EB.BP]MOBJECT/SRC_GETORIGPATH.o: EB.BP/SRC_GETORIGPATH.b
	BASIC EB.BP SRC_GETORIGPATH.b

EB.BP]MOBJECT/SRC_GETPWD.o: EB.BP/SRC_GETPWD.b
	BASIC EB.BP SRC_GETPWD.b

EB.BP]MOBJECT/SRC_GETROOT.o: EB.BP/SRC_GETROOT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_GETROOT.b

EB.BP]MOBJECT/SRC_GET_REPOSITORY.o: EB.BP/SRC_GET_REPOSITORY.b
	BASIC EB.BP SRC_GET_REPOSITORY.b

EB.BP]MOBJECT/SRC_HISTORY.o: EB.BP/SRC_HISTORY.b
	BASIC EB.BP SRC_HISTORY.b

EB.BP]MOBJECT/SRC_OPENHIST.o: EB.BP/SRC_OPENHIST.b
	BASIC EB.BP SRC_OPENHIST.b

EB.BP]MOBJECT/SRC_OPENLOCKS.o: EB.BP/SRC_OPENLOCKS.b
	BASIC EB.BP SRC_OPENLOCKS.b

EB.BP]MOBJECT/SRC_READ.o: EB.BP/SRC_READ.b
	BASIC EB.BP SRC_READ.b

EB.BP]MOBJECT/SRC_READHIST.o: EB.BP/SRC_READHIST.b EB.INCLUDES/GET.USER EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_READHIST.b

EB.BP]MOBJECT/SRC_REMOVEHIST.o: EB.BP/SRC_REMOVEHIST.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_REMOVEHIST.b

EB.BP]MOBJECT/SRC_REPOSITORY.o: EB.BP/SRC_REPOSITORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_REPOSITORY.b

EB.BP]MOBJECT/SRC_REVERT.o: EB.BP/SRC_REVERT.b
	BASIC EB.BP SRC_REVERT.b

EB.BP]MOBJECT/SRC_SENTENCE.o: EB.BP/SRC_SENTENCE.b EB.INCLUDES/DISPLAY.SYNTAX EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_SENTENCE.b

EB.BP]MOBJECT/SRC_SRC_STATUS.o: EB.BP/SRC_SRC_STATUS.b
	BASIC EB.BP SRC_SRC_STATUS.b

EB.BP]MOBJECT/SRC_SYNC.o: EB.BP/SRC_SYNC.b
	BASIC EB.BP SRC_SYNC.b

EB.BP]MOBJECT/SRC_UPDATEHIST.o: EB.BP/SRC_UPDATEHIST.b EB.INCLUDES/GET.USER EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SRC_UPDATEHIST.b

EB.BP]MOBJECT/SVNCHECKOUT.o: EB.BP/SVNCHECKOUT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVNCHECKOUT.b

bin/SVNCHECKOUT: EB.BP]MOBJECT/SVNCHECKOUT.o
	CATALOG -o./bin EB.BP SVNCHECKOUT.b

EB.BP]MOBJECT/SVNCOMMIT.o: EB.BP/SVNCOMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVNCOMMIT.b

bin/SVNCOMMIT: EB.BP]MOBJECT/SVNCOMMIT.o
	CATALOG -o./bin EB.BP SVNCOMMIT.b

EB.BP]MOBJECT/SVNDELETE.o: EB.BP/SVNDELETE.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVNDELETE.b

bin/SVNDELETE: EB.BP]MOBJECT/SVNDELETE.o
	CATALOG -o./bin EB.BP SVNDELETE.b

EB.BP]MOBJECT/SVNRENAME.o: EB.BP/SVNRENAME.b
	BASIC EB.BP SVNRENAME.b

bin/SVNRENAME: EB.BP]MOBJECT/SVNRENAME.o
	CATALOG -o./bin EB.BP SVNRENAME.b

EB.BP]MOBJECT/SVNREVERT.o: EB.BP/SVNREVERT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVNREVERT.b

bin/SVNREVERT: EB.BP]MOBJECT/SVNREVERT.o
	CATALOG -o./bin EB.BP SVNREVERT.b

EB.BP]MOBJECT/SVNSELECT.o: EB.BP/SVNSELECT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVNSELECT.b

bin/SVNSELECT: EB.BP]MOBJECT/SVNSELECT.o
	CATALOG -o./bin EB.BP SVNSELECT.b

EB.BP]MOBJECT/SVN_ADD.o: EB.BP/SVN_ADD.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_ADD.b

EB.BP]MOBJECT/SVN_CHECKIN.o: EB.BP/SVN_CHECKIN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_CHECKIN.b

EB.BP]MOBJECT/SVN_CHECKOUT.o: EB.BP/SVN_CHECKOUT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_CHECKOUT.b

EB.BP]MOBJECT/SVN_CLEAN.o: EB.BP/SVN_CLEAN.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_CLEAN.b

EB.BP]MOBJECT/SVN_COMMIT.o: EB.BP/SVN_COMMIT.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_COMMIT.b

EB.BP]MOBJECT/SVN_DELETE.o: EB.BP/SVN_DELETE.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_DELETE.b

EB.BP]MOBJECT/SVN_EXEC.o: EB.BP/SVN_EXEC.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_EXEC.b

EB.BP]MOBJECT/SVN_GETCATLID.o: EB.BP/SVN_GETCATLID.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_GETCATLID.b

EB.BP]MOBJECT/SVN_GETHOMEPATH.o: EB.BP/SVN_GETHOMEPATH.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_GETHOMEPATH.b

EB.BP]MOBJECT/SVN_GETORIGPATH.o: EB.BP/SVN_GETORIGPATH.b
	BASIC EB.BP SVN_GETORIGPATH.b

EB.BP]MOBJECT/SVN_GETPWD.o: EB.BP/SVN_GETPWD.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_GETPWD.b

EB.BP]MOBJECT/SVN_GETROOT.o: EB.BP/SVN_GETROOT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_GETROOT.b

EB.BP]MOBJECT/SVN_GET_REPOSITORY.o: EB.BP/SVN_GET_REPOSITORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_GET_REPOSITORY.b

EB.BP]MOBJECT/SVN_HISTORY.o: EB.BP/SVN_HISTORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_HISTORY.b

EB.BP]MOBJECT/SVN_READ.o: EB.BP/SVN_READ.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_READ.b

EB.BP]MOBJECT/SVN_REPOSITORY.o: EB.BP/SVN_REPOSITORY.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_REPOSITORY.b

EB.BP]MOBJECT/SVN_REVERT.o: EB.BP/SVN_REVERT.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_REVERT.b

EB.BP]MOBJECT/SVN_SRC_STATUS.o: EB.BP/SVN_SRC_STATUS.b EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_SRC_STATUS.b

EB.BP]MOBJECT/SVN_SYNC.o: EB.BP/SVN_SYNC.b EB.INCLUDES/GET.HOME EB.INCLUDES/SRC_DEBUG
	BASIC EB.BP SVN_SYNC.b

EB.BP]MOBJECT/UNCOMPILED.o: EB.BP/UNCOMPILED.b
	BASIC EB.BP UNCOMPILED.b

bin/UNCOMPILED: EB.BP]MOBJECT/UNCOMPILED.o
	CATALOG -o./bin EB.BP UNCOMPILED.b

EB.BP]MOBJECT/color.o: EB.BP/color.b
	BASIC EB.BP color.b

bin/color: EB.BP]MOBJECT/color.o
	CATALOG -o./bin EB.BP color.b

EB.BP]MOBJECT/initColors.o: EB.BP/initColors.b EB.EQUS/COLOURS EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP initColors.b

EB.BP]MOBJECT/isComment.o: EB.BP/isComment.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isComment.b

EB.BP]MOBJECT/isNumber.o: EB.BP/isNumber.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isNumber.b

EB.BP]MOBJECT/isReservedWord.o: EB.BP/isReservedWord.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isReservedWord.b

EB.BP]MOBJECT/isSeparator.o: EB.BP/isSeparator.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isSeparator.b

EB.BP]MOBJECT/isSpacer.o: EB.BP/isSpacer.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isSpacer.b

EB.BP]MOBJECT/isString.o: EB.BP/isString.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP isString.b

EB.BP]MOBJECT/jEDIfmt.o: EB.BP/jEDIfmt.b
	BASIC EB.BP jEDIfmt.b

bin/jEDIfmt: EB.BP]MOBJECT/jEDIfmt.o
	CATALOG -o./bin EB.BP jEDIfmt.b

EB.BP]MOBJECT/lex.o: EB.BP/lex.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP lex.b

bin/lex: EB.BP]MOBJECT/lex.o
	CATALOG -o./bin EB.BP lex.b

EB.BP]MOBJECT/lexLine.o: EB.BP/lexLine.b EB.INCLUDES/lex.h EB.INCLUDES/lexCharTypes.h EB.INCLUDES/lexEquates.h
	BASIC EB.BP lexLine.b

EB.BP]MOBJECT/nextToken.o: EB.BP/nextToken.b EB.INCLUDES/lexCharTypes.h
	BASIC EB.BP nextToken.b

EB.BP]MOBJECT/stringType.o: EB.BP/stringType.b EB.INCLUDES/lexEquates.h
	BASIC EB.BP stringType.b

EB.BP]MOBJECT/ttvt220_TRANS.o: EB.BP/ttvt220_TRANS.b
	BASIC EB.BP ttvt220_TRANS.b

lib/lib.el: EB.BP]MOBJECT/EBGETHOME.o EB.BP]MOBJECT/EBGETKEY.o EB.BP]MOBJECT/EBJSHOW.o EB.BP]MOBJECT/EB_ADD.o EB.BP]MOBJECT/EB_ANCHAR.o EB.BP]MOBJECT/EB_ASSIGN_OPEN.o EB.BP]MOBJECT/EB_AUTOSAVE.o EB.BP]MOBJECT/EB_BOX.o EB.BP]MOBJECT/EB_CHOICES.o EB.BP]MOBJECT/EB_CH_COLOUR.o EB.BP]MOBJECT/EB_CLOSE.o EB.BP]MOBJECT/EB_COMPARE.o EB.BP]MOBJECT/EB_CONVCODE.o EB.BP]MOBJECT/EB_CUT.o EB.BP]MOBJECT/EB_EREPLACE.o EB.BP]MOBJECT/EB_ERRMSG.o EB.BP]MOBJECT/EB_EXPANDFLNM.o EB.BP]MOBJECT/EB_FILE.o EB.BP]MOBJECT/EB_FIND.o EB.BP]MOBJECT/EB_FINDDEC.o EB.BP]MOBJECT/EB_FORMAT.o EB.BP]MOBJECT/EB_GETMOUSE.o EB.BP]MOBJECT/EB_GETRPL.o EB.BP]MOBJECT/EB_GETTCC.o EB.BP]MOBJECT/EB_GET_INPUT.o EB.BP]MOBJECT/EB_HELP.o EB.BP]MOBJECT/EB_INP.o EB.BP]MOBJECT/EB_INPUT.o EB.BP]MOBJECT/EB_INPUT_ZERO.o EB.BP]MOBJECT/EB_INTEGRATE.o EB.BP]MOBJECT/EB_MAKEHIST.o EB.BP]MOBJECT/EB_MARKADJ.o EB.BP]MOBJECT/EB_MERGE.o EB.BP]MOBJECT/EB_MERRMSG.o EB.BP]MOBJECT/EB_MOVE.o EB.BP]MOBJECT/EB_OPEN.o EB.BP]MOBJECT/EB_OPEN_FILE.o EB.BP]MOBJECT/EB_PASTE.o EB.BP]MOBJECT/EB_PRINT.o EB.BP]MOBJECT/EB_READHEADERS.o EB.BP]MOBJECT/EB_READINCL.o EB.BP]MOBJECT/EB_REFINE.o EB.BP]MOBJECT/EB_REFRESH.o EB.BP]MOBJECT/EB_REGEX.o EB.BP]MOBJECT/EB_REPLACE.o EB.BP]MOBJECT/EB_ROTATE.o EB.BP]MOBJECT/EB_RSS.o EB.BP]MOBJECT/EB_SEARCH.o EB.BP]MOBJECT/EB_SETUPSWITCH.o EB.BP]MOBJECT/EB_SHOWMEMBERS.o EB.BP]MOBJECT/EB_SWAP.o EB.BP]MOBJECT/EB_TABCOL.o EB.BP]MOBJECT/EB_TABS.o EB.BP]MOBJECT/EB_TCL.o EB.BP]MOBJECT/EB_TRIM.o EB.BP]MOBJECT/EB_UT_BOX.o EB.BP]MOBJECT/EB_UT_INIT.o EB.BP]MOBJECT/EB_UT_INPUT_ZERO.o EB.BP]MOBJECT/EB_UT_WP.o EB.BP]MOBJECT/EB_VERSION.o EB.BP]MOBJECT/EB_VERS_CTRL.o EB.BP]MOBJECT/FNKEYTRANS.o EB.BP]MOBJECT/GETFLNM.o EB.BP]MOBJECT/GETFULLPATH.o EB.BP]MOBJECT/GETSRCTYPE.o EB.BP]MOBJECT/GETYN.o EB.BP]MOBJECT/GET_CATALOG_FILE.o EB.BP]MOBJECT/GET_CATALOG_FILES.o EB.BP]MOBJECT/GIT_ADD.o EB.BP]MOBJECT/GIT_CHECKIN.o EB.BP]MOBJECT/GIT_CHECKOUT.o EB.BP]MOBJECT/GIT_CLEAN.o EB.BP]MOBJECT/GIT_COMMIT.o EB.BP]MOBJECT/GIT_DELETE.o EB.BP]MOBJECT/GIT_EXEC.o EB.BP]MOBJECT/GIT_GETCATLID.o EB.BP]MOBJECT/GIT_GETHOMEPATH.o EB.BP]MOBJECT/GIT_GETORIGPATH.o EB.BP]MOBJECT/GIT_GETPWD.o EB.BP]MOBJECT/GIT_GETROOT.o EB.BP]MOBJECT/GIT_GET_REPOSITORY.o EB.BP]MOBJECT/GIT_HISTORY.o EB.BP]MOBJECT/GIT_READ.o EB.BP]MOBJECT/GIT_REPOSITORY.o EB.BP]MOBJECT/GIT_REVERT.o EB.BP]MOBJECT/GIT_SRC_STATUS.o EB.BP]MOBJECT/GIT_SYNC.o EB.BP]MOBJECT/JBCUserConversions.o EB.BP]MOBJECT/SPLITFILEPATH.o EB.BP]MOBJECT/SRCPUSH.o EB.BP]MOBJECT/SRC_ADD.o EB.BP]MOBJECT/SRC_CASE.o EB.BP]MOBJECT/SRC_CHECKIN.o EB.BP]MOBJECT/SRC_CHECKOUT.o EB.BP]MOBJECT/SRC_CLEAN.o EB.BP]MOBJECT/SRC_COMMIT.o EB.BP]MOBJECT/SRC_DELETE.o EB.BP]MOBJECT/SRC_EXEC.o EB.BP]MOBJECT/SRC_GETCATLID.o EB.BP]MOBJECT/SRC_GETHOMEPATH.o EB.BP]MOBJECT/SRC_GETORIGPATH.o EB.BP]MOBJECT/SRC_GETPWD.o EB.BP]MOBJECT/SRC_GETROOT.o EB.BP]MOBJECT/SRC_GET_REPOSITORY.o EB.BP]MOBJECT/SRC_HISTORY.o EB.BP]MOBJECT/SRC_OPENHIST.o EB.BP]MOBJECT/SRC_OPENLOCKS.o EB.BP]MOBJECT/SRC_READ.o EB.BP]MOBJECT/SRC_READHIST.o EB.BP]MOBJECT/SRC_REMOVEHIST.o EB.BP]MOBJECT/SRC_REPOSITORY.o EB.BP]MOBJECT/SRC_REVERT.o EB.BP]MOBJECT/SRC_SENTENCE.o EB.BP]MOBJECT/SRC_SRC_STATUS.o EB.BP]MOBJECT/SRC_SYNC.o EB.BP]MOBJECT/SRC_UPDATEHIST.o EB.BP]MOBJECT/SVN_ADD.o EB.BP]MOBJECT/SVN_CHECKIN.o EB.BP]MOBJECT/SVN_CHECKOUT.o EB.BP]MOBJECT/SVN_CLEAN.o EB.BP]MOBJECT/SVN_COMMIT.o EB.BP]MOBJECT/SVN_DELETE.o EB.BP]MOBJECT/SVN_EXEC.o EB.BP]MOBJECT/SVN_GETCATLID.o EB.BP]MOBJECT/SVN_GETHOMEPATH.o EB.BP]MOBJECT/SVN_GETORIGPATH.o EB.BP]MOBJECT/SVN_GETPWD.o EB.BP]MOBJECT/SVN_GETROOT.o EB.BP]MOBJECT/SVN_GET_REPOSITORY.o EB.BP]MOBJECT/SVN_HISTORY.o EB.BP]MOBJECT/SVN_READ.o EB.BP]MOBJECT/SVN_REPOSITORY.o EB.BP]MOBJECT/SVN_REVERT.o EB.BP]MOBJECT/SVN_SRC_STATUS.o EB.BP]MOBJECT/SVN_SYNC.o EB.BP]MOBJECT/initColors.o EB.BP]MOBJECT/isComment.o EB.BP]MOBJECT/isNumber.o EB.BP]MOBJECT/isReservedWord.o EB.BP]MOBJECT/isSeparator.o EB.BP]MOBJECT/isSpacer.o EB.BP]MOBJECT/isString.o EB.BP]MOBJECT/lexLine.o EB.BP]MOBJECT/nextToken.o EB.BP]MOBJECT/stringType.o EB.BP]MOBJECT/ttvt220_TRANS.o
	$(catlib)

rebuild: $(libobjs) $(binobjs)
	CATALOG -L./lib -o./bin EB.BP COMPARE_ITEM COMPL COMPL2 CONVF2DIR D3BASIC EB EBCRT EBFIND EBGETHOME EBGETKEY EBJSHOW EBKEYS EBKEYTEST EBL EBTTCOPY EBV EB_ADD EB_ANCHAR EB_ASSIGN_OPEN EB_AUTOSAVE EB_BGCOMPILE EB_BOX EB_CHOICES EB_CH_COLOUR EB_CLOSE EB_COMPARE EB_CONVCODE EB_CUT EB_ENABLE EB_EREPLACE EB_ERRMSG EB_EXPANDFLNM EB_FILE EB_FIND EB_FINDDEC EB_FORMAT EB_GETMOUSE EB_GETRPL EB_GETTCC EB_GET_INPUT EB_HELP EB_INP EB_INPUT EB_INPUT_ZERO EB_INTEGRATE EB_MAKEHIST EB_MARKADJ EB_MERGE EB_MERRMSG EB_MOVE EB_OPEN EB_OPEN_FILE EB_PASTE EB_PRINT EB_READHEADERS EB_READINCL EB_REFINE EB_REFRESH EB_REGEX EB_REPLACE EB_ROTATE EB_RSS EB_SEARCH EB_SETUPSWITCH EB_SHOWMEMBERS EB_SWAP EB_TABCOL EB_TABS EB_TCL EB_TRIM EB_UT_BOX EB_UT_INIT EB_UT_INPUT_ZERO EB_UT_WP EB_VERSION EB_VERS_CTRL FNKEYTRANS GETFLNM GETFULLPATH GETSAME GETSRCTYPE GETYN GET_CATALOG_FILE GET_CATALOG_FILES GITCHECKOUT GITCOMMIT GITDELETE GITRENAME GITREVERT GITSELECT GIT_ADD GIT_CHECKIN GIT_CHECKOUT GIT_CLEAN GIT_COMMIT GIT_DELETE GIT_EXEC GIT_GETCATLID GIT_GETHOMEPATH GIT_GETORIGPATH GIT_GETPWD GIT_GETROOT GIT_GET_REPOSITORY GIT_HISTORY GIT_READ GIT_REPOSITORY GIT_REVERT GIT_SRC_STATUS GIT_SYNC JBCUserConversions SPLITFILEPATH SRCCHECKOUT SRCCOMMIT SRCDELETE SRCPUSH SRCRENAME SRCREVERT SRCSELECT SRC_ADD SRC_CASE SRC_CHECKIN SRC_CHECKOUT SRC_CLEAN SRC_COMMIT SRC_DELETE SRC_EXEC SRC_GETCATLID SRC_GETHOMEPATH SRC_GETORIGPATH SRC_GETPWD SRC_GETROOT SRC_GET_REPOSITORY SRC_HISTORY SRC_OPENHIST SRC_OPENLOCKS SRC_READ SRC_READHIST SRC_REMOVEHIST SRC_REPOSITORY SRC_REVERT SRC_SENTENCE SRC_SRC_STATUS SRC_SYNC SRC_UPDATEHIST SVNCHECKOUT SVNCOMMIT SVNDELETE SVNRENAME SVNREVERT SVNSELECT SVN_ADD SVN_CHECKIN SVN_CHECKOUT SVN_CLEAN SVN_COMMIT SVN_DELETE SVN_EXEC SVN_GETCATLID SVN_GETHOMEPATH SVN_GETORIGPATH SVN_GETPWD SVN_GETROOT SVN_GET_REPOSITORY SVN_HISTORY SVN_READ SVN_REPOSITORY SVN_REVERT SVN_SRC_STATUS SVN_SYNC UNCOMPILED color initColors isComment isNumber isReservedWord isSeparator isSpacer isString jEDIfmt lex lexLine nextToken stringType ttvt220_TRANS

clean:
	-rm ./lib/lib.el
