    SUBROUTINE EB_AUTOSAVE
    INCLUDE EB.EQUS EB.COMMONS
    COM GEX(50),EXTRAS(50)
    COM EB.FILES(100),EB.FILE.LIST
    COM RDSP(100), CHANGES(100)
    GO MAIN$
    INCLUDE EB.EQUS OTHER.PARAMS
    INCLUDE EB.EQUS EB.EQUS
    EQU AM TO CHAR(254)
    MAIN$:!
    WRITE PSTIME:AM:REC ON JET.PASTE,ITNM:'.sav'
    PREV.TIME=TIME()
    RETURN
END
