    SUBROUTINE EB_ASSIGN_OPEN(FILE.NAME,POS,FILE.VAR,MUST.EXIST)
!
    INCLUDE EB.EQUS EB.COMMONS
    INCLUDE EB.OS.INCLUDES OS.ERRORS
!
    CALL EB_OPEN_FILE(FILE.NAME,POS)
    IF POS THEN
        FILE.VAR=OPENED.FILES(POS)
    END ELSE
        IF MUST.EXIST THEN STOP OPER,FILE.NAME
    END
    RETURN
END
