    SUBROUTINE EB_ANCHAR(I,ST,FI,TYPE,STMP)
    EQU PC TO 'P(1N);(1A)'
    INCR=1-2*(ST>FI)
    IF TYPE THEN
        FOR I=ST TO FI STEP INCR UNTIL NOT(ICONV(STMP[I,1],PC)#''); NEXT I
    END ELSE
        FOR I=ST TO FI STEP INCR UNTIL NOT(ICONV(STMP[I,1],PC)#''); NEXT I
    END
    RETURN
END
