    SUBROUTINE EB_ADD(START,LCOL,LLEN,INS.MODE,NEW.CHARS,CURR.LINE)
    EQU MAX TO 9999
    IF NOT(START) THEN START=LCOL
    LLEN=LEN(CURR.LINE)
    IF LLEN<START THEN
        CURR.LINE:=SPACE(START-LLEN)
    END
    IF INS.MODE THEN LLEN=0 ELSE LLEN=LEN(NEW.CHARS)
    CURR.LINE=(CURR.LINE[1,START-1]:NEW.CHARS:CURR.LINE[START+LLEN,MAX])
    START=0; NEW.CHARS=""
    RETURN
END
