    SUBROUTINE EB_AUTOSAVE
    INCLUDE EB.EQUS EB.COMMON
    GO MAIN$
    INCLUDE EB.EQUS OTHER.PARAMS
    INCLUDE EB.EQUS EB.EQUS
    EQU AM TO CHAR(254)
    MAIN$:!
    WRITE PSTIME:AM:REC ON JET.PASTE,ITNM:'.sav'
    PREV.TIME=TIME()
    RETURN
END
